ALTER TYPE "NotificationEvent" ADD VALUE IF NOT EXISTS 'CREDITS_EXPIRING';
ALTER TYPE "NotificationEvent" ADD VALUE IF NOT EXISTS 'STREAK_AT_RISK';
ALTER TYPE "NotificationEvent" ADD VALUE IF NOT EXISTS 'MOMENT_OF_NEED';
ALTER TYPE "NotificationEvent" ADD VALUE IF NOT EXISTS 'WELCOME_CREDITS';
ALTER TYPE "NotificationEvent" ADD VALUE IF NOT EXISTS 'WELCOME_CREDITS_REMINDER';
