/**
 * GET /api/admin/impersonate/[token]
 *
 * Consumes a one-time impersonation token (generated by
 * /api/admin/impersonate?userId=…) and starts impersonation by setting a
 * SEPARATE `eterapy-imp` cookie. The real session cookie is never touched, so
 * the superadmin stays a superadmin on admin.eterapy.com (B1).
 *
 * Security:
 * - One-time token (deleted on first use), 5-minute TTL.
 * - Only an ADMIN/SUPERADMIN can start impersonation.
 * - Cannot impersonate a SUPERADMIN or a blocked/deleted user.
 */
import { NextRequest, NextResponse } from "next/server";
import db from "@/lib/db";
import { auth } from "@/lib/auth";
import { adminUrl, appUrl } from "@/lib/subdomain";
import { encodeImpersonationToken, setImpersonationCookie } from "@/lib/impersonation";

function expiredPage() {
  return new NextResponse(
    `<!DOCTYPE html><html lang="ru"><head><meta charset="utf-8"><title>Ошибка</title>
    <style>body{font-family:sans-serif;background:#0e1628;color:#e8e0d4;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0}
    .card{background:#1a2438;border:1px solid #2a3448;border-radius:16px;padding:40px;max-width:420px;text-align:center}
    h2{color:#ef4444}a{color:#c9a96e}</style></head>
    <body><div class="card"><h2>❌ Ссылка устарела</h2>
    <p style="color:#8899aa">Токен недействителен или истёк (TTL: 5 минут).</p>
    <p><a href="/admin/clients">← Вернуться в панель</a></p></div></body></html>`,
    { status: 410, headers: { "Content-Type": "text/html; charset=utf-8" } },
  );
}

export async function GET(req: NextRequest, { params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;

  // Only an admin/superadmin may start impersonation. The real session is
  // present here because we never overwrote it.
  const session = await auth();
  const impersonatorId = session?.user?.id;
  if (!impersonatorId || !["ADMIN", "SUPERADMIN"].includes(session?.user?.role ?? "")) {
    return NextResponse.redirect(new URL(adminUrl("/admin"), req.url));
  }

  const record = await db.telegramLinkToken.findUnique({ where: { token: `imp:${token}` } });
  if (!record || record.expiresAt < new Date()) return expiredPage();

  // One-time use
  await db.telegramLinkToken.delete({ where: { token: `imp:${token}` } });

  const target = await db.user.findUnique({
    where: { id: record.userId },
    select: { id: true, role: true, blockedAt: true, deletedAt: true },
  });
  if (!target || target.blockedAt || target.deletedAt || target.role === "SUPERADMIN") {
    return NextResponse.redirect(new URL(adminUrl("/admin/clients"), req.url));
  }

  const cabinet = target.role === "PRACTITIONER" ? "/cabinet/practitioner" : "/cabinet";
  const impToken = await encodeImpersonationToken({ targetUserId: target.id, impersonatorId, targetRole: target.role });

  const response = NextResponse.redirect(new URL(appUrl(cabinet), req.url));
  setImpersonationCookie(response, impToken);
  return response;
}
