import type { SemanticPhrase } from "../semantic-core-types";

// «Разбор переписки» — 150 фраз, замер Wordstat 27.07.2026 (Россия, broad).
// Порог отбора — 100 показов в месяц: фразы ниже в ядро не попадают.
export const CHAT_ANALYSIS_PHRASES: readonly SemanticPhrase[] = [
  { phrase: "муж изменяет", demand: 420056, priority: "P1", intent: "смешанный" },
  { phrase: "жена изменяет", demand: 381885, priority: "P1", intent: "смешанный" },
  { phrase: "муж изменяет жене", demand: 176796, priority: "P1", intent: "смешанный" },
  { phrase: "как понять мужчину", demand: 74986, priority: "P1", intent: "информационный" },
  { phrase: "как понять что ты нравишься", demand: 14281, priority: "P1", intent: "информационный" },
  { phrase: "жена изменяет с другом", demand: 13079, priority: "P1", intent: "смешанный" },
  { phrase: "переписка с мужчиной", demand: 9657, priority: "P1", intent: "смешанный" },
  { phrase: "как понять бывшего мужчину", demand: 5802, priority: "P1", intent: "информационный" },
  { phrase: "как понять любимого мужчины", demand: 5324, priority: "P1", intent: "информационный" },
  { phrase: "как понять любящего мужчину", demand: 5107, priority: "P1", intent: "информационный" },
  { phrase: "как понять что мужчина влюблен", demand: 3732, priority: "P1", intent: "информационный" },
  { phrase: "как понять что ты нравишься парню", demand: 3484, priority: "P1", intent: "информационный" },
  { phrase: "как узнать что жена изменяет", demand: 3357, priority: "P1", intent: "коммерческий" },
  { phrase: "как понять что ты нравишься мужчине", demand: 3041, priority: "P1", intent: "информационный" },
  { phrase: "признаки измены", demand: 3041, priority: "P1", intent: "информационный" },
  { phrase: "как понять что ты нравишься девушке", demand: 2559, priority: "P1", intent: "информационный" },
  { phrase: "как понять мужчина говорит", demand: 2320, priority: "P1", intent: "информационный" },
  { phrase: "как понять какой мужчина", demand: 2167, priority: "P1", intent: "информационный" },
  { phrase: "как понять что мужчина признаки", demand: 1770, priority: "P1", intent: "информационный" },
  { phrase: "как понять что муж изменяет", demand: 1665, priority: "P1", intent: "информационный" },
  { phrase: "как понять что муж изменил", demand: 1665, priority: "P1", intent: "информационный" },
  { phrase: "как понять что мужчина тебя любит", demand: 1563, priority: "P1", intent: "информационный" },
  { phrase: "как понять что мужчина влюбился", demand: 1291, priority: "P1", intent: "информационный" },
  { phrase: "переписки мужчин с женщинами", demand: 1223, priority: "P1", intent: "смешанный" },
  { phrase: "как понять что ты нравишься человеку", demand: 1221, priority: "P1", intent: "информационный" },
  { phrase: "как узнать что муж изменяет", demand: 1127, priority: "P1", intent: "коммерческий" },
  { phrase: "как понять что мужчина скрывает", demand: 1097, priority: "P1", intent: "информационный" },
  { phrase: "переписка с другом мужчиной", demand: 1047, priority: "P1", intent: "смешанный" },
  { phrase: "как понять мужчину деву", demand: 1044, priority: "P1", intent: "информационный" },
  { phrase: "как понять коллегу мужчину", demand: 1044, priority: "P1", intent: "информационный" },
  { phrase: "как понять что мужчина женат", demand: 1015, priority: "P2", intent: "информационный" },
  { phrase: "начало переписки с мужчиной", demand: 935, priority: "P2", intent: "смешанный" },
  { phrase: "как понять слова мужчины", demand: 934, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина хочет тебя", demand: 907, priority: "P2", intent: "информационный" },
  { phrase: "признаки измены жены", demand: 867, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина серьезный", demand: 840, priority: "P2", intent: "информационный" },
  { phrase: "переписка с бывшим мужчиной", demand: 829, priority: "P2", intent: "смешанный" },
  { phrase: "мужчина ребенок как понять", demand: 820, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина изменил", demand: 810, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина изменяет", demand: 810, priority: "P2", intent: "информационный" },
  { phrase: "как по переписке понять что нравишься", demand: 810, priority: "P2", intent: "смешанный" },
  { phrase: "как понять что мужчина хочет женщину", demand: 717, priority: "P2", intent: "информационный" },
  { phrase: "как понять что человек мужчина", demand: 669, priority: "P2", intent: "информационный" },
  { phrase: "как понять друга мужчины", demand: 649, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина жену", demand: 646, priority: "P2", intent: "информационный" },
  { phrase: "как понять мужчину почему", demand: 628, priority: "P2", intent: "информационный" },
  { phrase: "как узнать изменяет ли жена", demand: 609, priority: "P2", intent: "коммерческий" },
  { phrase: "как понять что женщина нравится мужчине", demand: 606, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина разлюбил", demand: 601, priority: "P2", intent: "информационный" },
  { phrase: "как начать переписку с мужчиной", demand: 582, priority: "P2", intent: "коммерческий" },
  { phrase: "как понять скрытые чувства мужчины", demand: 573, priority: "P2", intent: "информационный" },
  { phrase: "как понять поведение мужчины", demand: 573, priority: "P2", intent: "информационный" },
  { phrase: "как понять мужчин психология", demand: 569, priority: "P2", intent: "информационный" },
  { phrase: "как понять мужчину по переписке", demand: 551, priority: "P2", intent: "информационный" },
  { phrase: "мужчина влюблен признаки как понять", demand: 549, priority: "P2", intent: "информационный" },
  { phrase: "признаки измены мужа", demand: 539, priority: "P2", intent: "информационный" },
  { phrase: "как понять что женщина любима мужчиной", demand: 518, priority: "P2", intent: "информационный" },
  { phrase: "знакомства переписка с мужчиной", demand: 513, priority: "P2", intent: "смешанный" },
  { phrase: "как понять что мужчина скрывает свои чувства", demand: 499, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина любит женщину", demand: 497, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина хочет бывшую", demand: 496, priority: "P2", intent: "информационный" },
  { phrase: "как понять намерения мужчины", demand: 491, priority: "P2", intent: "информационный" },
  { phrase: "как понять интерес мужчины", demand: 489, priority: "P2", intent: "информационный" },
  { phrase: "как понять скрытого влюбленного мужчину", demand: 486, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина без", demand: 484, priority: "P2", intent: "информационный" },
  { phrase: "как понять что скрыто нравишься", demand: 482, priority: "P2", intent: "информационный" },
  { phrase: "как понять фразы мужчины", demand: 479, priority: "P2", intent: "информационный" },
  { phrase: "как понять что ты нужна мужчине", demand: 468, priority: "P2", intent: "информационный" },
  { phrase: "переписка год с мужчиной", demand: 465, priority: "P2", intent: "смешанный" },
  { phrase: "как понять что парень нравится девушке", demand: 462, priority: "P2", intent: "информационный" },
  { phrase: "мужчина много как понять", demand: 455, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина влюблен но скрывает", demand: 451, priority: "P2", intent: "информационный" },
  { phrase: "как понять мужчину не общается", demand: 444, priority: "P2", intent: "информационный" },
  { phrase: "как понять мужчину серьезные отношения", demand: 440, priority: "P2", intent: "информационный" },
  { phrase: "как по взгляду понять что нравишься", demand: 434, priority: "P2", intent: "смешанный" },
  { phrase: "как понять тип мужчины", demand: 428, priority: "P2", intent: "информационный" },
  { phrase: "как понять настрой мужчины", demand: 426, priority: "P2", intent: "информационный" },
  { phrase: "как понять взрослого мужчину", demand: 423, priority: "P2", intent: "информационный" },
  { phrase: "как понять как настроен мужчина", demand: 416, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина сильный", demand: 411, priority: "P2", intent: "информационный" },
  { phrase: "как понять симпатию мужчины", demand: 409, priority: "P2", intent: "информационный" },
  { phrase: "как понять что у мужчины проблемы", demand: 407, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина делает", demand: 402, priority: "P2", intent: "информационный" },
  { phrase: "как понять что нравишься коллеге мужчине", demand: 402, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина хочет отношений", demand: 396, priority: "P2", intent: "информационный" },
  { phrase: "мужчине понравилась женщина как понять", demand: 386, priority: "P2", intent: "информационный" },
  { phrase: "как понять что ты нравишься коллеге", demand: 383, priority: "P2", intent: "информационный" },
  { phrase: "как понять что заинтересовала мужчину", demand: 380, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина заинтересован", demand: 380, priority: "P2", intent: "информационный" },
  { phrase: "как понять что нравишься парню по переписке", demand: 379, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчине на работе", demand: 369, priority: "P2", intent: "информационный" },
  { phrase: "как понять что ты нравишься другу", demand: 369, priority: "P2", intent: "информационный" },
  { phrase: "как понять ревность мужчины", demand: 368, priority: "P2", intent: "информационный" },
  { phrase: "как понять мужчина потерянный", demand: 367, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина не вернется", demand: 366, priority: "P2", intent: "информационный" },
  { phrase: "как понять что это твой мужчина", demand: 365, priority: "P2", intent: "информационный" },
  { phrase: "очевидные признаки измены", demand: 364, priority: "P2", intent: "информационный" },
  { phrase: "переписка с мужчиной примеры", demand: 364, priority: "P2", intent: "смешанный" },
  { phrase: "переписка мужчины с другими женщинами", demand: 361, priority: "P2", intent: "смешанный" },
  { phrase: "как понять что мужчина проверяет", demand: 356, priority: "P2", intent: "информационный" },
  { phrase: "как общаться с мужчиной по переписке", demand: 356, priority: "P2", intent: "смешанный" },
  { phrase: "как понять серьезный настрой мужчины", demand: 348, priority: "P2", intent: "информационный" },
  { phrase: "признаки как понять что ты нравишься", demand: 348, priority: "P2", intent: "информационный" },
  { phrase: "как вести переписку с мужчинами", demand: 346, priority: "P2", intent: "смешанный" },
  { phrase: "как понять чувства мужчины коллеги", demand: 345, priority: "P2", intent: "информационный" },
  { phrase: "как понять что понравилась мужчине после", demand: 341, priority: "P2", intent: "информационный" },
  { phrase: "как понять чувства влюбленного мужчины", demand: 338, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина уходит", demand: 336, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина ревнует", demand: 333, priority: "P2", intent: "информационный" },
  { phrase: "признаки измены очевидные и неочевидные", demand: 330, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина по судьбе", demand: 329, priority: "P2", intent: "информационный" },
  { phrase: "как понять сообщения мужчины", demand: 327, priority: "P2", intent: "информационный" },
  { phrase: "как понять мужчину на расстоянии", demand: 327, priority: "P2", intent: "информационный" },
  { phrase: "первая переписка с мужчиной", demand: 327, priority: "P2", intent: "смешанный" },
  { phrase: "первые переписки с мужчиной", demand: 327, priority: "P2", intent: "смешанный" },
  { phrase: "переписка с мужчиной разговор", demand: 327, priority: "P2", intent: "смешанный" },
  { phrase: "как понять что любишь мужчину по настоящему", demand: 319, priority: "P2", intent: "информационный" },
  { phrase: "как понять любима ли ты мужчиной", demand: 319, priority: "P2", intent: "информационный" },
  { phrase: "как понять любит ли тебя мужчина", demand: 319, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина настроен серьезно", demand: 316, priority: "P2", intent: "информационный" },
  { phrase: "как понять просто мужчина хочет", demand: 311, priority: "P2", intent: "информационный" },
  { phrase: "как понять что ты нравишься бывшему", demand: 309, priority: "P2", intent: "информационный" },
  { phrase: "как понять внимание мужчины", demand: 308, priority: "P2", intent: "информационный" },
  { phrase: "как понять что у мужчины другая", demand: 308, priority: "P2", intent: "информационный" },
  { phrase: "как понять мужчина бросил", demand: 306, priority: "P2", intent: "информационный" },
  { phrase: "переписка с мужчиной на расстоянии", demand: 304, priority: "P2", intent: "смешанный" },
  { phrase: "как понять что ты бесплоден у мужчин", demand: 302, priority: "P2", intent: "информационный" },
  { phrase: "как понять нравишься ли ты мужчине", demand: 301, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина скучает", demand: 297, priority: "P2", intent: "информационный" },
  { phrase: "как понять отношение мужчины к женщине", demand: 296, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина испытал", demand: 294, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина готов", demand: 294, priority: "P2", intent: "информационный" },
  { phrase: "как понять что нравлюсь женатому", demand: 291, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина не напишет", demand: 287, priority: "P2", intent: "информационный" },
  { phrase: "признаки измены мужчины", demand: 286, priority: "P2", intent: "информационный" },
  { phrase: "как понять хочешь ли мужчину", demand: 277, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина потерял", demand: 273, priority: "P2", intent: "информационный" },
  { phrase: "как понять мужчина молчит", demand: 272, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина врет", demand: 272, priority: "P2", intent: "информационный" },
  { phrase: "как понять что обидела мужчину", demand: 270, priority: "P2", intent: "информационный" },
  { phrase: "как понять что мужчина расстался", demand: 268, priority: "P2", intent: "информационный" },
  { phrase: "как понять что нравишься мужчине признаки", demand: 268, priority: "P2", intent: "информационный" },
  { phrase: "как понять что ты нравишься женщине", demand: 266, priority: "P2", intent: "информационный" },
  { phrase: "переписка мужа с мужчинами", demand: 265, priority: "P2", intent: "смешанный" },
  { phrase: "интересная переписка с мужчиной", demand: 264, priority: "P2", intent: "смешанный" },
  { phrase: "переписка с мужчиной что хочет", demand: 264, priority: "P2", intent: "смешанный" },
  { phrase: "как понять что нравишься незнакомому", demand: 264, priority: "P2", intent: "информационный" },
  { phrase: "общение с мужчинами по переписке", demand: 259, priority: "P2", intent: "смешанный" },
  { phrase: "как понять мужчину в постели", demand: 258, priority: "P2", intent: "информационный" },
  { phrase: "признаки измены женщины", demand: 258, priority: "P2", intent: "информационный" },
] as const;
