import type { SemanticPhrase } from "../semantic-core-types";

// «Подробный разбор» — 150 фраз, замер Wordstat 27.07.2026 (Россия, broad).
// Порог отбора — 100 показов в месяц: фразы ниже в ядро не попадают.
export const DEEP_REPORT_PHRASES: readonly SemanticPhrase[] = [
  { phrase: "психологический", demand: 1041176, priority: "P1", intent: "смешанный" },
  { phrase: "психологическая помощь", demand: 75794, priority: "P1", intent: "смешанный" },
  { phrase: "психологические вопросы", demand: 73390, priority: "P1", intent: "смешанный" },
  { phrase: "психолог онлайн", demand: 61161, priority: "P1", intent: "коммерческий" },
  { phrase: "психологический центр", demand: 41162, priority: "P1", intent: "смешанный" },
  { phrase: "консультация психолога", demand: 35307, priority: "P1", intent: "коммерческий" },
  { phrase: "вопрос психологу", demand: 29611, priority: "P1", intent: "смешанный" },
  { phrase: "психологическая поддержка", demand: 21829, priority: "P1", intent: "смешанный" },
  { phrase: "психолог онлайн бесплатно", demand: 19511, priority: "P1", intent: "коммерческий" },
  { phrase: "ии психолог", demand: 12534, priority: "P1", intent: "смешанный" },
  { phrase: "врач психотерапевт", demand: 12078, priority: "P1", intent: "смешанный" },
  { phrase: "психологическая помощь бесплатно", demand: 11253, priority: "P1", intent: "коммерческий" },
  { phrase: "бесплатная психологическая помощь", demand: 11253, priority: "P1", intent: "коммерческий" },
  { phrase: "психолог онлайн консультация", demand: 10511, priority: "P1", intent: "коммерческий" },
  { phrase: "центр психологической помощи", demand: 9518, priority: "P1", intent: "смешанный" },
  { phrase: "психотерапевт это", demand: 6618, priority: "P1", intent: "информационный" },
  { phrase: "задать вопрос психологу", demand: 5654, priority: "P1", intent: "смешанный" },
  { phrase: "бесплатная консультация психолога", demand: 4572, priority: "P1", intent: "коммерческий" },
  { phrase: "какие вопросы задает психолог", demand: 3993, priority: "P1", intent: "смешанный" },
  { phrase: "психолог онлайн анонимно", demand: 3798, priority: "P1", intent: "коммерческий" },
  { phrase: "служба психологической помощи", demand: 3392, priority: "P1", intent: "смешанный" },
  { phrase: "бесплатный психолог онлайн анонимно бесплатно", demand: 3384, priority: "P1", intent: "коммерческий" },
  { phrase: "психолог онлайн консультация бесплатно", demand: 3035, priority: "P1", intent: "коммерческий" },
  { phrase: "ии психолог онлайн", demand: 2976, priority: "P1", intent: "коммерческий" },
  { phrase: "ответы психологов на вопросы", demand: 2931, priority: "P1", intent: "смешанный" },
  { phrase: "ии психолог бесплатно", demand: 2930, priority: "P1", intent: "коммерческий" },
  { phrase: "психолог онлайн чат", demand: 2762, priority: "P1", intent: "коммерческий" },
  { phrase: "психологические вопросы психологу", demand: 2644, priority: "P1", intent: "смешанный" },
  { phrase: "семейный психолог онлайн", demand: 2074, priority: "P1", intent: "коммерческий" },
  { phrase: "ии психолог онлайн бесплатно", demand: 1842, priority: "P1", intent: "коммерческий" },
  { phrase: "1 вопрос психолога", demand: 1757, priority: "P2", intent: "смешанный" },
  { phrase: "что нельзя делать при оказании психологической поддержки", demand: 1697, priority: "P2", intent: "смешанный" },
  { phrase: "семейный психолог консультация", demand: 1679, priority: "P2", intent: "коммерческий" },
  { phrase: "правильные вопросы психолога", demand: 1675, priority: "P2", intent: "смешанный" },
  { phrase: "консультация психолога ребенка", demand: 1646, priority: "P2", intent: "коммерческий" },
  { phrase: "детский психолог консультация", demand: 1553, priority: "P2", intent: "коммерческий" },
  { phrase: "детский психолог онлайн", demand: 1376, priority: "P2", intent: "коммерческий" },
  { phrase: "онлайн психолог сейчас", demand: 1341, priority: "P2", intent: "коммерческий" },
  { phrase: "психолог для подростка онлайн", demand: 1238, priority: "P2", intent: "коммерческий" },
  { phrase: "вопросы родителям психологу", demand: 1204, priority: "P2", intent: "смешанный" },
  { phrase: "служба психологической поддержки", demand: 1195, priority: "P2", intent: "смешанный" },
  { phrase: "психолог вопрос отношения", demand: 1158, priority: "P2", intent: "смешанный" },
  { phrase: "3 вопроса психологу", demand: 1151, priority: "P2", intent: "смешанный" },
  { phrase: "консультации психолога для родителей", demand: 1146, priority: "P2", intent: "коммерческий" },
  { phrase: "онлайн психолог бесплатно анонимно чат", demand: 1110, priority: "P2", intent: "коммерческий" },
  { phrase: "помощь психолога онлайн", demand: 1093, priority: "P2", intent: "коммерческий" },
  { phrase: "вопросы социальному психологу", demand: 1093, priority: "P2", intent: "смешанный" },
  { phrase: "вопросы консультанта психолога", demand: 1075, priority: "P2", intent: "смешанный" },
  { phrase: "вопросы тест психолога", demand: 1017, priority: "P2", intent: "коммерческий" },
  { phrase: "вопросы теста психолога", demand: 1017, priority: "P2", intent: "коммерческий" },
  { phrase: "что делает психотерапевт", demand: 1011, priority: "P2", intent: "смешанный" },
  { phrase: "вопросы с правильными ответами психолога", demand: 1000, priority: "P2", intent: "смешанный" },
  { phrase: "хороший психолог онлайн", demand: 940, priority: "P2", intent: "коммерческий" },
  { phrase: "психолог консультация сейчас", demand: 926, priority: "P2", intent: "коммерческий" },
  { phrase: "психология вопрос психологу", demand: 899, priority: "P2", intent: "смешанный" },
  { phrase: "психолог онлайн консультация сейчас", demand: 866, priority: "P2", intent: "коммерческий" },
  { phrase: "основные вопросы психолога", demand: 866, priority: "P2", intent: "смешанный" },
  { phrase: "4 вопроса психолога", demand: 864, priority: "P2", intent: "смешанный" },
  { phrase: "консультация взрослого психолога", demand: 863, priority: "P2", intent: "коммерческий" },
  { phrase: "вопрос психологу можно", demand: 858, priority: "P2", intent: "смешанный" },
  { phrase: "консультация психолог клиент", demand: 839, priority: "P2", intent: "коммерческий" },
  { phrase: "психолог для подростка онлайн бесплатно", demand: 818, priority: "P2", intent: "коммерческий" },
  { phrase: "вопросов психологу консультация", demand: 807, priority: "P2", intent: "коммерческий" },
  { phrase: "вопросы медицинскому психологу", demand: 788, priority: "P2", intent: "смешанный" },
  { phrase: "психолог онлайн бесплатно анонимно без", demand: 780, priority: "P2", intent: "коммерческий" },
  { phrase: "консультация психолога тема", demand: 778, priority: "P2", intent: "коммерческий" },
  { phrase: "какие вопросы у психолога", demand: 757, priority: "P2", intent: "смешанный" },
  { phrase: "индивидуальная консультация психолога", demand: 736, priority: "P2", intent: "коммерческий" },
  { phrase: "первые вопросы психолога", demand: 733, priority: "P2", intent: "смешанный" },
  { phrase: "первый вопрос психолога", demand: 733, priority: "P2", intent: "смешанный" },
  { phrase: "семейный психолог онлайн консультация", demand: 728, priority: "P2", intent: "коммерческий" },
  { phrase: "психолог без консультаций", demand: 721, priority: "P2", intent: "коммерческий" },
  { phrase: "клинический психолог онлайн", demand: 715, priority: "P2", intent: "коммерческий" },
  { phrase: "вопросы психолога родителям ребенка", demand: 706, priority: "P2", intent: "смешанный" },
  { phrase: "суть консультации психолога", demand: 693, priority: "P2", intent: "коммерческий" },
  { phrase: "стоимость консультации психолога", demand: 689, priority: "P2", intent: "коммерческий" },
  { phrase: "вопросы практическому психологу", demand: 668, priority: "P2", intent: "смешанный" },
  { phrase: "помощь психолога онлайн бесплатно", demand: 656, priority: "P2", intent: "коммерческий" },
  { phrase: "5 вопросов психологу", demand: 645, priority: "P2", intent: "смешанный" },
  { phrase: "психолог онлайн бесплатно сейчас", demand: 643, priority: "P2", intent: "коммерческий" },
  { phrase: "консультация психолога родителям детей", demand: 642, priority: "P2", intent: "коммерческий" },
  { phrase: "вопросы помогающие психологу", demand: 640, priority: "P2", intent: "смешанный" },
  { phrase: "виды вопросов психолога", demand: 624, priority: "P2", intent: "информационный" },
  { phrase: "чат с психологом онлайн бесплатно", demand: 609, priority: "P2", intent: "коммерческий" },
  { phrase: "как отвечать на вопросы психолога", demand: 591, priority: "P2", intent: "коммерческий" },
  { phrase: "анонимная консультация психолога", demand: 587, priority: "P2", intent: "коммерческий" },
  { phrase: "психологи вопрос почему", demand: 582, priority: "P2", intent: "информационный" },
  { phrase: "проводить консультация психологов", demand: 566, priority: "P2", intent: "коммерческий" },
  { phrase: "вопрос ответ психолог родителям", demand: 561, priority: "P2", intent: "смешанный" },
  { phrase: "детский психолог вопросы", demand: 550, priority: "P2", intent: "смешанный" },
  { phrase: "хороший психолог онлайн бесплатно", demand: 541, priority: "P2", intent: "коммерческий" },
  { phrase: "психолог онлайн круглосуточно", demand: 527, priority: "P2", intent: "коммерческий" },
  { phrase: "взрослый психолог онлайн", demand: 526, priority: "P2", intent: "коммерческий" },
  { phrase: "консультация психолога онлайн анонимно", demand: 522, priority: "P2", intent: "коммерческий" },
  { phrase: "онлайн психолог для подростков анонимно", demand: 519, priority: "P2", intent: "коммерческий" },
  { phrase: "бесплатная консультация психолога анонимно", demand: 515, priority: "P2", intent: "коммерческий" },
  { phrase: "вопросы семейных психологов", demand: 513, priority: "P2", intent: "смешанный" },
  { phrase: "вопрос психологу онлайн", demand: 511, priority: "P2", intent: "коммерческий" },
  { phrase: "вопрос клиническому психологу", demand: 509, priority: "P2", intent: "смешанный" },
  { phrase: "вопросы психологов на приеме", demand: 506, priority: "P2", intent: "смешанный" },
  { phrase: "консультации медицинский психолог", demand: 504, priority: "P2", intent: "коммерческий" },
  { phrase: "найти психолога онлайн", demand: 500, priority: "P2", intent: "коммерческий" },
  { phrase: "консультация психолога онлайн бесплатно анонимно", demand: 493, priority: "P2", intent: "коммерческий" },
  { phrase: "психологическая консультация психолога", demand: 490, priority: "P2", intent: "коммерческий" },
  { phrase: "психолог онлайн недорого", demand: 488, priority: "P2", intent: "коммерческий" },
  { phrase: "психолог для подростка онлайн бесплатно анонимно", demand: 487, priority: "P2", intent: "коммерческий" },
  { phrase: "10 вопросов психологу", demand: 484, priority: "P2", intent: "смешанный" },
  { phrase: "вопросы решаемые психологом", demand: 481, priority: "P2", intent: "смешанный" },
  { phrase: "ответы психолога на вопросы клиентов", demand: 475, priority: "P2", intent: "смешанный" },
  { phrase: "консультация психолога чат", demand: 463, priority: "P2", intent: "коммерческий" },
  { phrase: "семейный психолог онлайн бесплатно", demand: 453, priority: "P2", intent: "коммерческий" },
  { phrase: "клинический психолог консультация", demand: 450, priority: "P2", intent: "коммерческий" },
  { phrase: "консультация психолога недорого", demand: 437, priority: "P2", intent: "коммерческий" },
  { phrase: "тест вопросы ответы психолога", demand: 437, priority: "P2", intent: "коммерческий" },
  { phrase: "психолог кпт онлайн", demand: 436, priority: "P2", intent: "коммерческий" },
  { phrase: "бесплатный психолог онлайн круглосуточно", demand: 435, priority: "P2", intent: "коммерческий" },
  { phrase: "психолог онлайн консультация чат", demand: 429, priority: "P2", intent: "коммерческий" },
  { phrase: "психолог бесплатно онлайн без консультации", demand: 429, priority: "P2", intent: "коммерческий" },
  { phrase: "хорошие вопросы психолога", demand: 429, priority: "P2", intent: "смешанный" },
  { phrase: "вопросы психолога 6", demand: 428, priority: "P2", intent: "смешанный" },
  { phrase: "вопросы про психолога", demand: 428, priority: "P2", intent: "смешанный" },
  { phrase: "консультация психолога екатеринбург", demand: 427, priority: "P2", intent: "коммерческий" },
  { phrase: "прием психолога онлайн", demand: 424, priority: "P2", intent: "коммерческий" },
  { phrase: "психолог онлайн удаленно", demand: 424, priority: "P2", intent: "коммерческий" },
  { phrase: "вопросы психологу темы", demand: 423, priority: "P2", intent: "смешанный" },
  { phrase: "вопросы психолога к человеку", demand: 421, priority: "P2", intent: "смешанный" },
  { phrase: "консультация психолога чат бесплатно", demand: 420, priority: "P2", intent: "коммерческий" },
  { phrase: "психолог первая консультация", demand: 419, priority: "P2", intent: "коммерческий" },
  { phrase: "детский психолог онлайн консультация", demand: 410, priority: "P2", intent: "коммерческий" },
  { phrase: "консультация психолога семье", demand: 408, priority: "P2", intent: "коммерческий" },
  { phrase: "что делает психолог вопрос", demand: 408, priority: "P2", intent: "смешанный" },
  { phrase: "время консультации психолога", demand: 407, priority: "P2", intent: "коммерческий" },
  { phrase: "вопросы психолога на медкомиссии", demand: 406, priority: "P2", intent: "смешанный" },
  { phrase: "нужна консультация психолога", demand: 401, priority: "P2", intent: "коммерческий" },
  { phrase: "стагнация в психологии", demand: 396, priority: "P2", intent: "смешанный" },
  { phrase: "журнал консультация психолога", demand: 388, priority: "P2", intent: "коммерческий" },
  { phrase: "пройти консультацию психолога", demand: 384, priority: "P2", intent: "коммерческий" },
  { phrase: "дети задают вопросы психологу", demand: 384, priority: "P2", intent: "смешанный" },
  { phrase: "психолог детям онлайн", demand: 374, priority: "P2", intent: "коммерческий" },
  { phrase: "рационализация в психологии", demand: 369, priority: "P2", intent: "смешанный" },
  { phrase: "работать психологом онлайн", demand: 365, priority: "P2", intent: "коммерческий" },
  { phrase: "вакансия психолог удаленно онлайн", demand: 364, priority: "P2", intent: "коммерческий" },
  { phrase: "вопрос специальному психологу", demand: 363, priority: "P2", intent: "смешанный" },
  { phrase: "вопрос психологу бесплатно", demand: 362, priority: "P2", intent: "коммерческий" },
  { phrase: "русский психолог онлайн", demand: 360, priority: "P2", intent: "коммерческий" },
  { phrase: "год психолог онлайн", demand: 358, priority: "P2", intent: "коммерческий" },
  { phrase: "начинающие психологи консультации", demand: 356, priority: "P2", intent: "коммерческий" },
  { phrase: "психолог онлайн 24", demand: 355, priority: "P2", intent: "коммерческий" },
  { phrase: "психолог онлайн консультация бесплатно в чате", demand: 352, priority: "P2", intent: "коммерческий" },
  { phrase: "психолог вопросы пациенту", demand: 352, priority: "P2", intent: "смешанный" },
] as const;
