import type { SemanticPhrase } from "../semantic-core-types";

// «Семейные вопросы» — 75 фраз, замер Wordstat 27.07.2026 (Россия, broad).
// Порог отбора — 100 показов в месяц: фразы ниже в ядро не попадают.
export const FAMILY_QUESTIONS_PHRASES: readonly SemanticPhrase[] = [
  { phrase: "семейные вопросы", demand: 21435, priority: "P1", intent: "смешанный" },
  { phrase: "отношения с родителями", demand: 13153, priority: "P1", intent: "смешанный" },
  { phrase: "семейные конфликты", demand: 5005, priority: "P1", intent: "смешанный" },
  { phrase: "взаимоотношения в семье", demand: 4366, priority: "P1", intent: "смешанный" },
  { phrase: "семейные вопросы и ответы", demand: 4036, priority: "P1", intent: "смешанный" },
  { phrase: "родовые программы", demand: 3899, priority: "P1", intent: "смешанный" },
  { phrase: "семейные вопросы в семье", demand: 2769, priority: "P1", intent: "смешанный" },
  { phrase: "деструктивная семья", demand: 1967, priority: "P1", intent: "смешанный" },
  { phrase: "семья отношения с родителями", demand: 1398, priority: "P1", intent: "смешанный" },
  { phrase: "отношения с родителями ответы", demand: 981, priority: "P1", intent: "смешанный" },
  { phrase: "семейные вопросы помощь", demand: 831, priority: "P1", intent: "смешанный" },
  { phrase: "семейные вопросы проблемы", demand: 693, priority: "P1", intent: "смешанный" },
  { phrase: "семейные вопросы для родителей", demand: 616, priority: "P1", intent: "смешанный" },
  { phrase: "плохие отношения с родителями", demand: 565, priority: "P1", intent: "смешанный" },
  { phrase: "деструктивная семья это", demand: 565, priority: "P1", intent: "информационный" },
  { phrase: "семейный конфликт в семье", demand: 544, priority: "P1", intent: "смешанный" },
  { phrase: "отношения с родителями девушки", demand: 525, priority: "P1", intent: "смешанный" },
  { phrase: "семейный конфликт дети", demand: 485, priority: "P1", intent: "смешанный" },
  { phrase: "какой семейный конфликт", demand: 477, priority: "P1", intent: "смешанный" },
  { phrase: "отношения с родителями парня", demand: 475, priority: "P1", intent: "смешанный" },
  { phrase: "взрослые отношения с родителями", demand: 463, priority: "P1", intent: "смешанный" },
  { phrase: "эмоциональные отношения с родителями", demand: 427, priority: "P1", intent: "смешанный" },
  { phrase: "отношения с родителями после", demand: 402, priority: "P1", intent: "смешанный" },
  { phrase: "про отношения с родителями", demand: 393, priority: "P1", intent: "смешанный" },
  { phrase: "темы отношения с родителями", demand: 352, priority: "P1", intent: "смешанный" },
  { phrase: "женская родовая программа", demand: 306, priority: "P1", intent: "смешанный" },
  { phrase: "доверительные отношения с родителями", demand: 304, priority: "P1", intent: "смешанный" },
  { phrase: "отношения с родителями мужа", demand: 278, priority: "P1", intent: "смешанный" },
  { phrase: "как наладить отношения с родителями", demand: 270, priority: "P1", intent: "информационный" },
  { phrase: "важные семейные вопросы", demand: 262, priority: "P1", intent: "смешанный" },
  { phrase: "родовые программы по женской линии", demand: 262, priority: "P2", intent: "смешанный" },
  { phrase: "отношения с родителями сочинение", demand: 251, priority: "P2", intent: "смешанный" },
  { phrase: "семейные вопросы мероприятие", demand: 247, priority: "P2", intent: "смешанный" },
  { phrase: "родовые программы судьбы", demand: 240, priority: "P2", intent: "смешанный" },
  { phrase: "сложные отношения с родителями", demand: 239, priority: "P2", intent: "смешанный" },
  { phrase: "отношения с родителями в возрасте", demand: 235, priority: "P2", intent: "смешанный" },
  { phrase: "межличностные отношения с родителями", demand: 225, priority: "P2", intent: "смешанный" },
  { phrase: "став отношения с родителями", demand: 220, priority: "P2", intent: "смешанный" },
  { phrase: "семейный конфликт является", demand: 212, priority: "P2", intent: "смешанный" },
  { phrase: "родовая программа программа рода", demand: 205, priority: "P2", intent: "смешанный" },
  { phrase: "ваши отношения с родителями", demand: 201, priority: "P2", intent: "смешанный" },
  { phrase: "какими должны быть отношения с родителями", demand: 198, priority: "P2", intent: "смешанный" },
  { phrase: "родовые программы в матрице", demand: 196, priority: "P2", intent: "смешанный" },
  { phrase: "отношения с родителями учеников", demand: 196, priority: "P2", intent: "смешанный" },
  { phrase: "отношения с родителями влияние", demand: 193, priority: "P2", intent: "смешанный" },
  { phrase: "отношения с родителями учащегося", demand: 189, priority: "P2", intent: "смешанный" },
  { phrase: "какие родовые программы", demand: 183, priority: "P2", intent: "смешанный" },
  { phrase: "семейный конфликт относится", demand: 181, priority: "P2", intent: "смешанный" },
  { phrase: "семейные конфликты типы", demand: 178, priority: "P2", intent: "смешанный" },
  { phrase: "семейный конфликт решение", demand: 166, priority: "P2", intent: "смешанный" },
  { phrase: "отношения с родителями виды", demand: 165, priority: "P2", intent: "информационный" },
  { phrase: "партнерские отношения с родителями", demand: 162, priority: "P2", intent: "смешанный" },
  { phrase: "близкие отношения с родителями", demand: 152, priority: "P2", intent: "смешанный" },
  { phrase: "семейные вопросы для детей и родителей", demand: 150, priority: "P2", intent: "смешанный" },
  { phrase: "отношения с родителями супруга", demand: 150, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы отношения с родителями", demand: 145, priority: "P2", intent: "смешанный" },
  { phrase: "отношения с родителями жены", demand: 142, priority: "P2", intent: "смешанный" },
  { phrase: "семейные вопросы для друг друга", demand: 139, priority: "P2", intent: "смешанный" },
  { phrase: "родовые программы в матрице судьбы", demand: 139, priority: "P2", intent: "смешанный" },
  { phrase: "эмоциональные семейные конфликты", demand: 135, priority: "P2", intent: "смешанный" },
  { phrase: "сложные семейные вопросы", demand: 134, priority: "P2", intent: "смешанный" },
  { phrase: "родовые программы по мужской", demand: 132, priority: "P2", intent: "смешанный" },
  { phrase: "отношения с родителями истории", demand: 131, priority: "P2", intent: "информационный" },
  { phrase: "беседа с детьми отношения с родителями", demand: 130, priority: "P2", intent: "смешанный" },
  { phrase: "родовые программы по мужской линии", demand: 127, priority: "P2", intent: "смешанный" },
  { phrase: "интересные семейные вопросы", demand: 125, priority: "P2", intent: "смешанный" },
  { phrase: "как выстроить отношения с родителями", demand: 124, priority: "P2", intent: "смешанный" },
  { phrase: "семейные вопросы онлайн", demand: 121, priority: "P2", intent: "коммерческий" },
  { phrase: "тест на отношения с родителями", demand: 121, priority: "P2", intent: "коммерческий" },
  { phrase: "отношения с родителями влияют на", demand: 120, priority: "P2", intent: "смешанный" },
  { phrase: "как наладить ребенку отношения с родителями", demand: 113, priority: "P2", intent: "информационный" },
  { phrase: "семейный конфликт особенности", demand: 102, priority: "P2", intent: "смешанный" },
  { phrase: "консультация отношения с родителями", demand: 101, priority: "P2", intent: "коммерческий" },
  { phrase: "теплые отношения с родителями", demand: 100, priority: "P2", intent: "смешанный" },
  { phrase: "семейные конфликты родители и дети", demand: 100, priority: "P2", intent: "смешанный" },
] as const;
