import type { SemanticPhrase } from "../semantic-core-types";

// «Гороскоп» — 150 фраз, замер Wordstat 27.07.2026 (Россия, broad).
// Порог отбора — 100 показов в месяц: фразы ниже в ядро не попадают.
export const HORARY_PHRASES: readonly SemanticPhrase[] = [
  { phrase: "предсказание", demand: 462799, priority: "P1", intent: "смешанный" },
  { phrase: "точный гороскоп", demand: 123563, priority: "P1", intent: "смешанный" },
  { phrase: "что меня ждет", demand: 114639, priority: "P1", intent: "смешанный" },
  { phrase: "таро да нет", demand: 109980, priority: "P1", intent: "смешанный" },
  { phrase: "самый точный гороскоп", demand: 84859, priority: "P1", intent: "смешанный" },
  { phrase: "гадание на будущее", demand: 68351, priority: "P1", intent: "смешанный" },
  { phrase: "гороскоп бесплатно", demand: 59099, priority: "P1", intent: "коммерческий" },
  { phrase: "точный гороскоп мужчина", demand: 56981, priority: "P1", intent: "смешанный" },
  { phrase: "гороскоп рождения", demand: 51412, priority: "P1", intent: "смешанный" },
  { phrase: "таро да или нет", demand: 50928, priority: "P1", intent: "смешанный" },
  { phrase: "самый точный гороскоп мужчина", demand: 42055, priority: "P1", intent: "смешанный" },
  { phrase: "гадание на будущее онлайн", demand: 38510, priority: "P1", intent: "коммерческий" },
  { phrase: "точный гороскоп бесплатно", demand: 34484, priority: "P1", intent: "коммерческий" },
  { phrase: "гадание на будущее бесплатно", demand: 32854, priority: "P1", intent: "коммерческий" },
  { phrase: "гадание на будущее онлайн бесплатно", demand: 29630, priority: "P1", intent: "коммерческий" },
  { phrase: "карты таро да нет", demand: 24068, priority: "P1", intent: "смешанный" },
  { phrase: "карта да или нет", demand: 19711, priority: "P1", intent: "смешанный" },
  { phrase: "мечи да или нет", demand: 19432, priority: "P1", intent: "смешанный" },
  { phrase: "жезлы да или нет", demand: 18853, priority: "P1", intent: "смешанный" },
  { phrase: "пентакли да или нет", demand: 18756, priority: "P1", intent: "смешанный" },
  { phrase: "гадание да или нет", demand: 18696, priority: "P1", intent: "смешанный" },
  { phrase: "таро да нет значение", demand: 16977, priority: "P1", intent: "информационный" },
  { phrase: "таро да нет онлайн", demand: 16827, priority: "P1", intent: "коммерческий" },
  { phrase: "кубки да или нет", demand: 16307, priority: "P1", intent: "смешанный" },
  { phrase: "гадание на ситуацию", demand: 13334, priority: "P1", intent: "смешанный" },
  { phrase: "гадание таро да нет", demand: 12833, priority: "P1", intent: "смешанный" },
  { phrase: "правдивое гадание на будущее", demand: 11812, priority: "P1", intent: "смешанный" },
  { phrase: "карты таро да или нет", demand: 11392, priority: "P1", intent: "смешанный" },
  { phrase: "значение таро да или нет", demand: 11271, priority: "P1", intent: "информационный" },
  { phrase: "точный гороскоп лев", demand: 11084, priority: "P1", intent: "смешанный" },
  { phrase: "предсказание будущего", demand: 10876, priority: "P2", intent: "смешанный" },
  { phrase: "бесплатное правдивое гадание на будущее онлайн", demand: 10349, priority: "P2", intent: "коммерческий" },
  { phrase: "таро предсказание", demand: 9510, priority: "P2", intent: "смешанный" },
  { phrase: "что меня ждет в ближайшем", demand: 9027, priority: "P2", intent: "смешанный" },
  { phrase: "самый точный гороскоп лев", demand: 8761, priority: "P2", intent: "смешанный" },
  { phrase: "да или нет гадание онлайн", demand: 7948, priority: "P2", intent: "коммерческий" },
  { phrase: "да нет таро мечи", demand: 7904, priority: "P2", intent: "смешанный" },
  { phrase: "гадание что меня ждет", demand: 7653, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на ситуацию онлайн", demand: 7351, priority: "P2", intent: "коммерческий" },
  { phrase: "гадание на будущее таро бесплатно", demand: 7216, priority: "P2", intent: "коммерческий" },
  { phrase: "что меня ждет в будущем", demand: 6549, priority: "P2", intent: "смешанный" },
  { phrase: "таро что меня ждет", demand: 6528, priority: "P2", intent: "смешанный" },
  { phrase: "что меня ждет с бывшим", demand: 6454, priority: "P2", intent: "смешанный" },
  { phrase: "мечи да или нет таро", demand: 6281, priority: "P2", intent: "смешанный" },
  { phrase: "ответ да нет таро", demand: 5956, priority: "P2", intent: "смешанный" },
  { phrase: "что меня ждет днем", demand: 5470, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на ситуацию бесплатно", demand: 5164, priority: "P2", intent: "коммерческий" },
  { phrase: "что меня ждет в ближайшем будущем", demand: 4964, priority: "P2", intent: "смешанный" },
  { phrase: "кубки таро да или нет", demand: 4938, priority: "P2", intent: "смешанный" },
  { phrase: "что меня ждет онлайн", demand: 4392, priority: "P2", intent: "коммерческий" },
  { phrase: "что меня ждет там", demand: 4252, priority: "P2", intent: "смешанный" },
  { phrase: "будущее россии предсказания", demand: 4166, priority: "P2", intent: "смешанный" },
  { phrase: "расклад таро да нет", demand: 3990, priority: "P2", intent: "смешанный" },
  { phrase: "точное гадание на будущее", demand: 3988, priority: "P2", intent: "смешанный" },
  { phrase: "таро бесплатно да нет", demand: 3895, priority: "P2", intent: "коммерческий" },
  { phrase: "карта вопрос да или нет", demand: 3629, priority: "P2", intent: "смешанный" },
  { phrase: "что меня ждет гадание онлайн", demand: 3492, priority: "P2", intent: "коммерческий" },
  { phrase: "таро да нет онлайн бесплатно", demand: 3435, priority: "P2", intent: "коммерческий" },
  { phrase: "таро онлайн да или нет", demand: 3344, priority: "P2", intent: "коммерческий" },
  { phrase: "что меня ждет дома", demand: 3342, priority: "P2", intent: "смешанный" },
  { phrase: "жезлы в таро да или нет", demand: 3328, priority: "P2", intent: "смешанный" },
  { phrase: "таро да нет перевернутое", demand: 3312, priority: "P2", intent: "смешанный" },
  { phrase: "пентакли в таро да или нет", demand: 3170, priority: "P2", intent: "смешанный" },
  { phrase: "значение карт да или нет", demand: 3116, priority: "P2", intent: "информационный" },
  { phrase: "гадание на будущее на кофейной", demand: 3083, priority: "P2", intent: "смешанный" },
  { phrase: "точный гороскоп для женщин", demand: 3066, priority: "P2", intent: "смешанный" },
  { phrase: "бесплатно что меня ждет", demand: 2986, priority: "P2", intent: "коммерческий" },
  { phrase: "гадание на будущее самому", demand: 2968, priority: "P2", intent: "смешанный" },
  { phrase: "гадание что меня ждет в будущем", demand: 2964, priority: "P2", intent: "смешанный" },
  { phrase: "точное гадание на ситуацию", demand: 2889, priority: "P2", intent: "смешанный" },
  { phrase: "карта таро онлайн гадание на будущее", demand: 2865, priority: "P2", intent: "коммерческий" },
  { phrase: "таро ответ да или нет", demand: 2835, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на ситуацию точное бесплатно", demand: 2778, priority: "P2", intent: "коммерческий" },
  { phrase: "куприянович что меня ждет", demand: 2775, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на ситуацию точное правдивое", demand: 2705, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на будущее самое точное", demand: 2695, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на ситуацию с точным ответом", demand: 2647, priority: "P2", intent: "смешанный" },
  { phrase: "таро на вопрос да или нет", demand: 2633, priority: "P2", intent: "смешанный" },
  { phrase: "что меня ждет на работе", demand: 2617, priority: "P2", intent: "смешанный" },
  { phrase: "карты ответ да или нет", demand: 2606, priority: "P2", intent: "смешанный" },
  { phrase: "что меня ждет 2", demand: 2549, priority: "P2", intent: "смешанный" },
  { phrase: "кофейное гадание на будущее бесплатно", demand: 2543, priority: "P2", intent: "коммерческий" },
  { phrase: "что меня ждет с мужем", demand: 2519, priority: "P2", intent: "смешанный" },
  { phrase: "что меня ждет месяц", demand: 2499, priority: "P2", intent: "смешанный" },
  { phrase: "значение карт таро да или нет", demand: 2457, priority: "P2", intent: "информационный" },
  { phrase: "раз что меня ждет", demand: 2457, priority: "P2", intent: "смешанный" },
  { phrase: "что меня ждет вечером", demand: 2384, priority: "P2", intent: "смешанный" },
  { phrase: "что меня ждет дальше", demand: 2343, priority: "P2", intent: "смешанный" },
  { phrase: "карты таро ответ да нет", demand: 2288, priority: "P2", intent: "смешанный" },
  { phrase: "кофейное гадание на будущее онлайн", demand: 2288, priority: "P2", intent: "коммерческий" },
  { phrase: "мама что меня ждет", demand: 2263, priority: "P2", intent: "смешанный" },
  { phrase: "карты таро гадание на ситуацию", demand: 2226, priority: "P2", intent: "смешанный" },
  { phrase: "что меня ждет парнем", demand: 2213, priority: "P2", intent: "смешанный" },
  { phrase: "бесплатное гадание да или нет", demand: 2191, priority: "P2", intent: "коммерческий" },
  { phrase: "гадание на ситуацию онлайн правдивое", demand: 2184, priority: "P2", intent: "коммерческий" },
  { phrase: "расклад что меня ждет", demand: 2168, priority: "P2", intent: "смешанный" },
  { phrase: "правдивое гадание на ситуацию онлайн бесплатно", demand: 2150, priority: "P2", intent: "коммерческий" },
  { phrase: "правдивый точный гороскоп", demand: 2148, priority: "P2", intent: "смешанный" },
  { phrase: "точное гадание на ситуацию онлайн бесплатно", demand: 2143, priority: "P2", intent: "коммерческий" },
  { phrase: "что меня ждет 1", demand: 2132, priority: "P2", intent: "смешанный" },
  { phrase: "мечи значение да или нет", demand: 2125, priority: "P2", intent: "информационный" },
  { phrase: "гадание на ситуацию онлайн бесплатно правдивое точное", demand: 2067, priority: "P2", intent: "коммерческий" },
  { phrase: "таро да нет рыцарь", demand: 2066, priority: "P2", intent: "смешанный" },
  { phrase: "что меня ждет сейчас", demand: 2061, priority: "P2", intent: "смешанный" },
  { phrase: "пентакли значение да или нет", demand: 2037, priority: "P2", intent: "информационный" },
  { phrase: "кофейное гадание на будущее онлайн бесплатно", demand: 2033, priority: "P2", intent: "коммерческий" },
  { phrase: "бесплатное гадание на будущее самое", demand: 2021, priority: "P2", intent: "коммерческий" },
  { phrase: "руны гадание на ситуацию", demand: 1958, priority: "P2", intent: "смешанный" },
  { phrase: "мечи перевернутые да или нет", demand: 1953, priority: "P2", intent: "смешанный" },
  { phrase: "кубки значение да или нет", demand: 1951, priority: "P2", intent: "информационный" },
  { phrase: "таро уэйта да нет", demand: 1945, priority: "P2", intent: "смешанный" },
  { phrase: "бесплатное гадание на будущее самое точное", demand: 1938, priority: "P2", intent: "коммерческий" },
  { phrase: "гадание онлайн бесплатно да или нет", demand: 1937, priority: "P2", intent: "коммерческий" },
  { phrase: "жезлы значение да или нет", demand: 1904, priority: "P2", intent: "информационный" },
  { phrase: "пажи таро да нет", demand: 1878, priority: "P2", intent: "смешанный" },
  { phrase: "гадание да или нет точное", demand: 1807, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на будущее самое точное онлайн", demand: 1784, priority: "P2", intent: "коммерческий" },
  { phrase: "жезлы перевернутая да или нет", demand: 1780, priority: "P2", intent: "смешанный" },
  { phrase: "пентакли таро значение да нет", demand: 1778, priority: "P2", intent: "информационный" },
  { phrase: "личный гороскоп", demand: 1771, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на будущее отношений", demand: 1770, priority: "P2", intent: "смешанный" },
  { phrase: "гадание таро да нет бесплатно", demand: 1761, priority: "P2", intent: "коммерческий" },
  { phrase: "пентакли перевернутая да или нет", demand: 1739, priority: "P2", intent: "смешанный" },
  { phrase: "кубки перевернутые да или нет", demand: 1706, priority: "P2", intent: "смешанный" },
  { phrase: "онлайн гадание что меня ждет ближайшее", demand: 1683, priority: "P2", intent: "коммерческий" },
  { phrase: "рыцарь да или нет таро", demand: 1640, priority: "P2", intent: "смешанный" },
  { phrase: "таро да нет 6", demand: 1588, priority: "P2", intent: "смешанный" },
  { phrase: "кубки таро значение да или нет", demand: 1586, priority: "P2", intent: "информационный" },
  { phrase: "что меня ждет в личной", demand: 1572, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на будущее онлайн бесплатно самые точные", demand: 1554, priority: "P2", intent: "коммерческий" },
  { phrase: "гадание на картах таро да нет", demand: 1550, priority: "P2", intent: "смешанный" },
  { phrase: "карты таро гадание на будущее правдивое", demand: 1527, priority: "P2", intent: "смешанный" },
  { phrase: "что меня ждет ночью", demand: 1505, priority: "P2", intent: "смешанный" },
  { phrase: "таро да нет точно", demand: 1493, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на будущее женщины", demand: 1480, priority: "P2", intent: "смешанный" },
  { phrase: "что меня ждет на этой неделе", demand: 1466, priority: "P2", intent: "информационный" },
  { phrase: "гадание на будущее руны", demand: 1465, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на картах да или нет", demand: 1454, priority: "P2", intent: "смешанный" },
  { phrase: "да нет таро 5", demand: 1449, priority: "P2", intent: "смешанный" },
  { phrase: "найти что меня ждет", demand: 1430, priority: "P2", intent: "смешанный" },
  { phrase: "карты таро на вопрос да или нет", demand: 1405, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на будущее расклады", demand: 1404, priority: "P2", intent: "смешанный" },
  { phrase: "расклад таро что меня ждет", demand: 1395, priority: "P2", intent: "смешанный" },
  { phrase: "что меня ждет в личной жизни", demand: 1386, priority: "P2", intent: "смешанный" },
  { phrase: "карты таро что меня ждет", demand: 1382, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на таро да или нет", demand: 1359, priority: "P2", intent: "смешанный" },
  { phrase: "мечи в таро значение да или нет", demand: 1329, priority: "P2", intent: "информационный" },
  { phrase: "что меня ждет минус", demand: 1314, priority: "P2", intent: "смешанный" },
  { phrase: "ответ да нет таро онлайн", demand: 1312, priority: "P2", intent: "коммерческий" },
  { phrase: "что меня ждет в любви", demand: 1308, priority: "P2", intent: "смешанный" },
] as const;
