import type { SemanticPhrase } from "../semantic-core-types";

// «Дизайн человека» — 106 фраз, замер Wordstat 27.07.2026 (Россия, broad).
// Порог отбора — 100 показов в месяц: фразы ниже в ядро не попадают.
export const HUMAN_DESIGN_PHRASES: readonly SemanticPhrase[] = [
  { phrase: "дизайн человека", demand: 49871, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека бесплатно", demand: 4988, priority: "P1", intent: "коммерческий" },
  { phrase: "human design", demand: 3312, priority: "P1", intent: "смешанный" },
  { phrase: "карта дизайн человека", demand: 3183, priority: "P1", intent: "смешанный" },
  { phrase: "ворота дизайн человека", demand: 2855, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека онлайн", demand: 2088, priority: "P1", intent: "коммерческий" },
  { phrase: "дизайн человека расчет", demand: 1666, priority: "P1", intent: "коммерческий" },
  { phrase: "дизайн человека расшифровка", demand: 1273, priority: "P1", intent: "смешанный" },
  { phrase: "проектор дизайн человека", demand: 1199, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека типы", demand: 1136, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека 2", demand: 1080, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека 4", demand: 976, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека 5", demand: 967, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека генератор", demand: 947, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека 6", demand: 931, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека совместимость", demand: 794, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека онлайн бесплатно", demand: 757, priority: "P1", intent: "коммерческий" },
  { phrase: "дизайн человека крест", demand: 657, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека расчет онлайн", demand: 640, priority: "P1", intent: "коммерческий" },
  { phrase: "генный дизайн человека", demand: 504, priority: "P1", intent: "смешанный" },
  { phrase: "генные ключи дизайн человека", demand: 502, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека по дате", demand: 501, priority: "P1", intent: "смешанный" },
  { phrase: "манифестор дизайн человека", demand: 484, priority: "P1", intent: "смешанный" },
  { phrase: "транзит дизайн человека", demand: 461, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека по дате рождения", demand: 445, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека линия", demand: 421, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека работа", demand: 418, priority: "P1", intent: "смешанный" },
  { phrase: "система дизайн человека", demand: 384, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека как называется", demand: 377, priority: "P1", intent: "смешанный" },
  { phrase: "русский дизайн человека", demand: 376, priority: "P1", intent: "смешанный" },
  { phrase: "дизайн человека про", demand: 365, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека расшифровка карты", demand: 353, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека расчет бесплатно", demand: 339, priority: "P2", intent: "коммерческий" },
  { phrase: "определить дизайн человека", demand: 336, priority: "P2", intent: "смешанный" },
  { phrase: "среда дизайн человека", demand: 320, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека на русском с расшифровкой", demand: 317, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека инкарнационный", demand: 308, priority: "P2", intent: "смешанный" },
  { phrase: "создать дизайн человека", demand: 302, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека 2 профиль", demand: 281, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека расшифровка онлайн", demand: 267, priority: "P2", intent: "коммерческий" },
  { phrase: "рефлектор дизайн человека", demand: 263, priority: "P2", intent: "смешанный" },
  { phrase: "рейв карта дизайн человека", demand: 259, priority: "P2", intent: "смешанный" },
  { phrase: "профиль 6 дизайн человека", demand: 254, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека расчет карты", demand: 251, priority: "P2", intent: "коммерческий" },
  { phrase: "дизайн человека цвета", demand: 248, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека 3 5", demand: 241, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека онлайн бесплатно с расшифровкой", demand: 241, priority: "P2", intent: "коммерческий" },
  { phrase: "дизайн человека название", demand: 229, priority: "P2", intent: "смешанный" },
  { phrase: "наука дизайн человека", demand: 228, priority: "P2", intent: "смешанный" },
  { phrase: "группа дизайн человека", demand: 225, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека психология", demand: 218, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека 1 3", demand: 215, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека профиль 5", demand: 211, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека карту бесплатно на русском", demand: 211, priority: "P2", intent: "коммерческий" },
  { phrase: "карта дизайн человека на русском", demand: 211, priority: "P2", intent: "смешанный" },
  { phrase: "построить дизайн человека", demand: 210, priority: "P2", intent: "коммерческий" },
  { phrase: "дизайн человека расшифровка карты на русском", demand: 208, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека авторитет", demand: 204, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека что значит", demand: 201, priority: "P2", intent: "информационный" },
  { phrase: "профиль 4 дизайн человека", demand: 199, priority: "P2", intent: "смешанный" },
  { phrase: "сделать дизайн человека", demand: 198, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека тест", demand: 194, priority: "P2", intent: "коммерческий" },
  { phrase: "дизайн человека вопросы", demand: 193, priority: "P2", intent: "смешанный" },
  { phrase: "проект дизайн человека", demand: 191, priority: "P2", intent: "смешанный" },
  { phrase: "техника дизайн человека", demand: 190, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека 9", demand: 185, priority: "P2", intent: "смешанный" },
  { phrase: "профиль 3 дизайн человека", demand: 184, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека 26", demand: 179, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека 5 2", demand: 179, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека по дате бесплатно", demand: 176, priority: "P2", intent: "коммерческий" },
  { phrase: "дизайн человека работает", demand: 176, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека виды", demand: 172, priority: "P2", intent: "информационный" },
  { phrase: "солнце дизайн человека", demand: 169, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека по дате рождения бесплатно", demand: 164, priority: "P2", intent: "коммерческий" },
  { phrase: "генетический дизайн человека", demand: 162, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека 39", demand: 161, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека 55", demand: 160, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека ворота линии", demand: 158, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека ворота описание", demand: 156, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека какие типы", demand: 156, priority: "P2", intent: "смешанный" },
  { phrase: "тон дизайн человека", demand: 156, priority: "P2", intent: "смешанный" },
  { phrase: "хьюмен дизайн человека", demand: 154, priority: "P2", intent: "смешанный" },
  { phrase: "генетическая травма дизайн человека", demand: 150, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека 35", demand: 149, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека 13", demand: 148, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека 21", demand: 148, priority: "P2", intent: "смешанный" },
  { phrase: "ра дизайн человека", demand: 146, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека калькулятор", demand: 144, priority: "P2", intent: "коммерческий" },
  { phrase: "дизайн человека расчет онлайн бесплатно", demand: 144, priority: "P2", intent: "коммерческий" },
  { phrase: "дизайн человека совместимость бесплатно", demand: 143, priority: "P2", intent: "коммерческий" },
  { phrase: "дизайн человека 28", demand: 143, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека 41", demand: 141, priority: "P2", intent: "смешанный" },
  { phrase: "отшельник дизайн человека", demand: 141, priority: "P2", intent: "смешанный" },
  { phrase: "текущий транзит дизайн человека", demand: 139, priority: "P2", intent: "смешанный" },
  { phrase: "тело дизайн человека", demand: 139, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека описание женщина", demand: 138, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека 62", demand: 136, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека открытые", demand: 135, priority: "P2", intent: "смешанный" },
  { phrase: "открой дизайн человека", demand: 131, priority: "P2", intent: "смешанный" },
  { phrase: "профиль 6 2 дизайн человека", demand: 131, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека ра уру", demand: 128, priority: "P2", intent: "смешанный" },
  { phrase: "генератор дизайн человека описание", demand: 127, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека 1 4", demand: 127, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека 58", demand: 126, priority: "P2", intent: "смешанный" },
  { phrase: "дизайн человека на русском языке", demand: 126, priority: "P2", intent: "смешанный" },
  { phrase: "тип проектор дизайн человека", demand: 114, priority: "P2", intent: "смешанный" },
] as const;
