import type { SemanticPhrase } from "../semantic-core-types";

// «Натальная карта» — 150 фраз, замер Wordstat 27.07.2026 (Россия, broad).
// Порог отбора — 100 показов в месяц: фразы ниже в ядро не попадают.
export const NATAL_CHART_PHRASES: readonly SemanticPhrase[] = [
  { phrase: "натальная карта", demand: 840340, priority: "P1", intent: "смешанный" },
  { phrase: "астрология", demand: 210780, priority: "P1", intent: "смешанный" },
  { phrase: "натальная карта онлайн", demand: 176523, priority: "P1", intent: "коммерческий" },
  { phrase: "асцендент", demand: 173467, priority: "P1", intent: "смешанный" },
  { phrase: "астролог", demand: 123362, priority: "P1", intent: "смешанный" },
  { phrase: "астрологический", demand: 87650, priority: "P1", intent: "смешанный" },
  { phrase: "натальная карта бесплатно", demand: 71998, priority: "P1", intent: "коммерческий" },
  { phrase: "натальная карта онлайн бесплатно", demand: 48574, priority: "P1", intent: "коммерческий" },
  { phrase: "астрологический прогноз", demand: 40384, priority: "P1", intent: "смешанный" },
  { phrase: "дома в натальной карте", demand: 26434, priority: "P1", intent: "смешанный" },
  { phrase: "натальная карта с расшифровкой", demand: 23877, priority: "P1", intent: "смешанный" },
  { phrase: "натальная карта рождения", demand: 21869, priority: "P1", intent: "смешанный" },
  { phrase: "натальная карта с расшифровкой бесплатно", demand: 20323, priority: "P1", intent: "коммерческий" },
  { phrase: "натальная карта по дате", demand: 20230, priority: "P1", intent: "смешанный" },
  { phrase: "асцендент по дате", demand: 19038, priority: "P1", intent: "смешанный" },
  { phrase: "дома в астрологии", demand: 18769, priority: "P1", intent: "смешанный" },
  { phrase: "асцендент рождения", demand: 18652, priority: "P1", intent: "смешанный" },
  { phrase: "натальная карта по дате рождения", demand: 18070, priority: "P1", intent: "смешанный" },
  { phrase: "асцендент по дате рождения", demand: 17280, priority: "P1", intent: "смешанный" },
  { phrase: "натальной карте женщины", demand: 17259, priority: "P1", intent: "смешанный" },
  { phrase: "натальная карта онлайн с расшифровкой", demand: 16334, priority: "P1", intent: "коммерческий" },
  { phrase: "натальная карта онлайн бесплатно с расшифровкой", demand: 15202, priority: "P1", intent: "коммерческий" },
  { phrase: "расчет натальной карты", demand: 15083, priority: "P1", intent: "коммерческий" },
  { phrase: "натальная карта расчет", demand: 14699, priority: "P1", intent: "коммерческий" },
  { phrase: "астрология это", demand: 14646, priority: "P1", intent: "информационный" },
  { phrase: "лунный знак", demand: 12986, priority: "P1", intent: "смешанный" },
  { phrase: "натальная карта по дате бесплатно", demand: 12371, priority: "P1", intent: "коммерческий" },
  { phrase: "асцендент онлайн", demand: 12283, priority: "P1", intent: "коммерческий" },
  { phrase: "асцендент женщины", demand: 11526, priority: "P1", intent: "смешанный" },
  { phrase: "натальная карта рождения бесплатно", demand: 10987, priority: "P1", intent: "коммерческий" },
  { phrase: "натальная карта с расшифровкой по дате", demand: 10869, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта по дате рождения бесплатно", demand: 10777, priority: "P2", intent: "коммерческий" },
  { phrase: "какой астрология", demand: 10521, priority: "P2", intent: "смешанный" },
  { phrase: "бесплатная натальная карта с расшифровкой по дате", demand: 10235, priority: "P2", intent: "коммерческий" },
  { phrase: "построить натальную карту", demand: 9458, priority: "P2", intent: "коммерческий" },
  { phrase: "расшифровка натальной карты рождения", demand: 9456, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта по дате рождения с расшифровкой", demand: 9341, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент бесплатно", demand: 9287, priority: "P2", intent: "коммерческий" },
  { phrase: "натальная карта построить", demand: 9233, priority: "P2", intent: "коммерческий" },
  { phrase: "натальная карта по дате онлайн", demand: 8871, priority: "P2", intent: "коммерческий" },
  { phrase: "натальная карта рождения с расшифровкой бесплатно", demand: 8754, priority: "P2", intent: "коммерческий" },
  { phrase: "расшифровка натальной карты бесплатно по дате рождения", demand: 8741, priority: "P2", intent: "коммерческий" },
  { phrase: "планеты в астрологии", demand: 8664, priority: "P2", intent: "смешанный" },
  { phrase: "луна в натальной карте", demand: 8620, priority: "P2", intent: "смешанный" },
  { phrase: "составляющие натальной карты", demand: 8481, priority: "P2", intent: "смешанный" },
  { phrase: "составить натальную карту", demand: 8479, priority: "P2", intent: "коммерческий" },
  { phrase: "за астрологию отвечает", demand: 8425, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта по дате онлайн бесплатно", demand: 8404, priority: "P2", intent: "коммерческий" },
  { phrase: "натальная карта рождения онлайн", demand: 7897, priority: "P2", intent: "коммерческий" },
  { phrase: "знак асцендента", demand: 7851, priority: "P2", intent: "смешанный" },
  { phrase: "венера в натальной карте", demand: 7801, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент в скорпионе", demand: 7680, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта по дате рождения онлайн", demand: 7529, priority: "P2", intent: "коммерческий" },
  { phrase: "натальная карта мужчины", demand: 7252, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта рождения онлайн бесплатно", demand: 7210, priority: "P2", intent: "коммерческий" },
  { phrase: "лунный знак зодиака", demand: 7118, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта онлайн бесплатно по дате рождения", demand: 7089, priority: "P2", intent: "коммерческий" },
  { phrase: "асценденты львов", demand: 6675, priority: "P2", intent: "смешанный" },
  { phrase: "астрология карта", demand: 6472, priority: "P2", intent: "смешанный" },
  { phrase: "солнце в натальной карте", demand: 6194, priority: "P2", intent: "смешанный" },
  { phrase: "марс в натальной карте", demand: 6108, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта суть", demand: 6070, priority: "P2", intent: "информационный" },
  { phrase: "года астрология", demand: 5890, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент карта", demand: 5876, priority: "P2", intent: "смешанный" },
  { phrase: "планеты в натальной карте", demand: 5785, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент мужчина", demand: 5703, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта качества", demand: 5591, priority: "P2", intent: "смешанный" },
  { phrase: "астрология онлайн", demand: 5336, priority: "P2", intent: "коммерческий" },
  { phrase: "астрология день", demand: 5320, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент натальная", demand: 5226, priority: "P2", intent: "смешанный" },
  { phrase: "знаки в астрологии", demand: 5107, priority: "P2", intent: "смешанный" },
  { phrase: "астро онлайн натальная", demand: 5067, priority: "P2", intent: "коммерческий" },
  { phrase: "асцендент в деве", demand: 4950, priority: "P2", intent: "смешанный" },
  { phrase: "юпитер в натальной карте", demand: 4848, priority: "P2", intent: "смешанный" },
  { phrase: "натальная астрология", demand: 4841, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта транзиты", demand: 4833, priority: "P2", intent: "смешанный" },
  { phrase: "дома в астрологии за что отвечают", demand: 4812, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент в раке", demand: 4773, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта асцендент", demand: 4676, priority: "P2", intent: "смешанный" },
  { phrase: "сатурн в натальной карте", demand: 4663, priority: "P2", intent: "смешанный" },
  { phrase: "что за что отвечает в натальной карте", demand: 4648, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент онлайн бесплатно", demand: 4628, priority: "P2", intent: "коммерческий" },
  { phrase: "натальная карта время", demand: 4619, priority: "P2", intent: "смешанный" },
  { phrase: "лилит в натальной карте", demand: 4618, priority: "P2", intent: "смешанный" },
  { phrase: "расчет натальной карты онлайн", demand: 4549, priority: "P2", intent: "коммерческий" },
  { phrase: "асцендент в весах", demand: 4516, priority: "P2", intent: "смешанный" },
  { phrase: "звезды в астрологии", demand: 4450, priority: "P2", intent: "смешанный" },
  { phrase: "соединение в натальной карте", demand: 4400, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта онлайн расчет", demand: 4349, priority: "P2", intent: "коммерческий" },
  { phrase: "что значит натальная карта", demand: 4345, priority: "P2", intent: "информационный" },
  { phrase: "асцендент по дате бесплатно", demand: 4344, priority: "P2", intent: "коммерческий" },
  { phrase: "астрология натальная карта", demand: 4305, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент дома", demand: 4297, priority: "P2", intent: "смешанный" },
  { phrase: "как узнать свой асцендент", demand: 4270, priority: "P2", intent: "коммерческий" },
  { phrase: "плутон в натальной карте", demand: 4265, priority: "P2", intent: "смешанный" },
  { phrase: "разбор натальной карты", demand: 4264, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент во льве", demand: 4254, priority: "P2", intent: "смешанный" },
  { phrase: "узнать асцендент по дате", demand: 4136, priority: "P2", intent: "коммерческий" },
  { phrase: "асцендент зодиака", demand: 4074, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент по дате рождения бесплатно", demand: 4068, priority: "P2", intent: "коммерческий" },
  { phrase: "асцендент знака зодиака", demand: 4007, priority: "P2", intent: "смешанный" },
  { phrase: "астрология бесплатно", demand: 3959, priority: "P2", intent: "коммерческий" },
  { phrase: "астро онлайн натальная карта", demand: 3905, priority: "P2", intent: "коммерческий" },
  { phrase: "астрология рождения", demand: 3889, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент в стрельце", demand: 3831, priority: "P2", intent: "смешанный" },
  { phrase: "астрология значение", demand: 3725, priority: "P2", intent: "информационный" },
  { phrase: "узнать асцендент по дате рождения", demand: 3668, priority: "P2", intent: "коммерческий" },
  { phrase: "асцендент по дате онлайн", demand: 3582, priority: "P2", intent: "коммерческий" },
  { phrase: "про астрологию", demand: 3539, priority: "P2", intent: "смешанный" },
  { phrase: "квадрат в натальной карте", demand: 3467, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент в козероге", demand: 3448, priority: "P2", intent: "смешанный" },
  { phrase: "меркурий в натальной карте", demand: 3433, priority: "P2", intent: "смешанный" },
  { phrase: "построить натальную карту онлайн", demand: 3380, priority: "P2", intent: "коммерческий" },
  { phrase: "7 дом в натальной карте", demand: 3369, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент рождения онлайн", demand: 3359, priority: "P2", intent: "коммерческий" },
  { phrase: "асцендент по дате рождения онлайн", demand: 3347, priority: "P2", intent: "коммерческий" },
  { phrase: "знаки в натальной карте", demand: 3254, priority: "P2", intent: "смешанный" },
  { phrase: "натальный карта online", demand: 3240, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент тельца", demand: 3111, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент в близнецах", demand: 3096, priority: "P2", intent: "смешанный" },
  { phrase: "скорпионы в натальной карте", demand: 3060, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта ли", demand: 3052, priority: "P2", intent: "смешанный" },
  { phrase: "соединение асцендентов", demand: 3028, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта львов", demand: 2984, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта лев", demand: 2971, priority: "P2", intent: "смешанный" },
  { phrase: "сделать натальную карту", demand: 2969, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта стрелец", demand: 2967, priority: "P2", intent: "смешанный" },
  { phrase: "уран в натальной карте", demand: 2930, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта 10", demand: 2923, priority: "P2", intent: "смешанный" },
  { phrase: "астрология человек", demand: 2914, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта 12", demand: 2867, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта рак", demand: 2839, priority: "P2", intent: "смешанный" },
  { phrase: "астрология воровка", demand: 2813, priority: "P2", intent: "смешанный" },
  { phrase: "8 в натальной карте", demand: 2810, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта рыбы", demand: 2803, priority: "P2", intent: "смешанный" },
  { phrase: "астрология 11", demand: 2801, priority: "P2", intent: "смешанный" },
  { phrase: "нептун в натальной карте", demand: 2792, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент в рыбах", demand: 2790, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент в овне", demand: 2780, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта расчет бесплатно", demand: 2778, priority: "P2", intent: "коммерческий" },
  { phrase: "построить натальную карту бесплатно", demand: 2777, priority: "P2", intent: "коммерческий" },
  { phrase: "12 астрология", demand: 2748, priority: "P2", intent: "смешанный" },
  { phrase: "асцендент в водолее", demand: 2739, priority: "P2", intent: "смешанный" },
  { phrase: "астрология знаки зодиака", demand: 2692, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта весы", demand: 2691, priority: "P2", intent: "смешанный" },
  { phrase: "арк сурвайвал асцендент", demand: 2683, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта билеты", demand: 2682, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта водолея", demand: 2660, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта 2", demand: 2658, priority: "P2", intent: "смешанный" },
  { phrase: "расчет асцендента", demand: 2641, priority: "P2", intent: "коммерческий" },
] as const;
