import type { SemanticPhrase } from "../semantic-core-types";

// «Матрица судьбы» — 150 фраз, замер Wordstat 27.07.2026 (Россия, broad).
// Порог отбора — 100 показов в месяц: фразы ниже в ядро не попадают.
export const NUMEROLOGY_PHRASES: readonly SemanticPhrase[] = [
  { phrase: "матрица судьбы", demand: 972380, priority: "P1", intent: "смешанный" },
  { phrase: "нумерология", demand: 554918, priority: "P1", intent: "смешанный" },
  { phrase: "нумерология значение", demand: 169702, priority: "P1", intent: "информационный" },
  { phrase: "нумерология чисел", demand: 74591, priority: "P1", intent: "смешанный" },
  { phrase: "матрица судьбы онлайн", demand: 74140, priority: "P1", intent: "коммерческий" },
  { phrase: "число рождения", demand: 73756, priority: "P1", intent: "смешанный" },
  { phrase: "матрица судьбы бесплатно", demand: 72582, priority: "P1", intent: "коммерческий" },
  { phrase: "матрица судьбы совместимость", demand: 62354, priority: "P1", intent: "смешанный" },
  { phrase: "нумерология рождения", demand: 52663, priority: "P1", intent: "смешанный" },
  { phrase: "нумерология по дате", demand: 42607, priority: "P1", intent: "смешанный" },
  { phrase: "нумерология по дате рождения", demand: 39489, priority: "P1", intent: "смешанный" },
  { phrase: "матрица судьбы онлайн бесплатно", demand: 31795, priority: "P1", intent: "коммерческий" },
  { phrase: "цифры в нумерологии", demand: 25559, priority: "P1", intent: "смешанный" },
  { phrase: "нумеролог", demand: 23873, priority: "P1", intent: "смешанный" },
  { phrase: "число судьбы", demand: 23778, priority: "P1", intent: "смешанный" },
  { phrase: "что означает в нумерологии", demand: 21359, priority: "P1", intent: "информационный" },
  { phrase: "матрица судьбы по дате", demand: 17772, priority: "P1", intent: "смешанный" },
  { phrase: "матрица судьбы по рождению", demand: 16291, priority: "P1", intent: "смешанный" },
  { phrase: "нумерология человека", demand: 15957, priority: "P1", intent: "смешанный" },
  { phrase: "матрица судьбы по дате рождения", demand: 15802, priority: "P1", intent: "смешанный" },
  { phrase: "нумерология женщин", demand: 15776, priority: "P1", intent: "смешанный" },
  { phrase: "нумерология совместимость", demand: 15618, priority: "P1", intent: "смешанный" },
  { phrase: "значение чисел в нумерологии", demand: 15526, priority: "P1", intent: "информационный" },
  { phrase: "матрица судьбы 8", demand: 15485, priority: "P1", intent: "смешанный" },
  { phrase: "матрица судьбы бесплатно с расшифровкой", demand: 14622, priority: "P1", intent: "коммерческий" },
  { phrase: "кармическая матрица судьбы", demand: 13469, priority: "P1", intent: "смешанный" },
  { phrase: "нумерология мужчина", demand: 12131, priority: "P1", intent: "смешанный" },
  { phrase: "что значит нумерология", demand: 11484, priority: "P1", intent: "информационный" },
  { phrase: "матрица судьбы 15", demand: 11359, priority: "P1", intent: "смешанный" },
  { phrase: "матрица судьбы онлайн с расшифровкой", demand: 10099, priority: "P1", intent: "коммерческий" },
  { phrase: "нумерология бесплатно", demand: 10016, priority: "P2", intent: "коммерческий" },
  { phrase: "матрица судьбы онлайн бесплатно с расшифровкой", demand: 9508, priority: "P2", intent: "коммерческий" },
  { phrase: "9 в нумерологии", demand: 9250, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы по дате бесплатно", demand: 8735, priority: "P2", intent: "коммерческий" },
  { phrase: "7 в нумерологии", demand: 8523, priority: "P2", intent: "смешанный" },
  { phrase: "что означают цифры в нумерологии", demand: 8432, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы сердце", demand: 8327, priority: "P2", intent: "смешанный" },
  { phrase: "6 в нумерологии", demand: 8264, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы значения", demand: 8228, priority: "P2", intent: "смешанный" },
  { phrase: "4 в нумерологии", demand: 7987, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология онлайн", demand: 7914, priority: "P2", intent: "коммерческий" },
  { phrase: "матрица судьбы по дате рождения бесплатно", demand: 7813, priority: "P2", intent: "коммерческий" },
  { phrase: "нумерология 21 21", demand: 7810, priority: "P2", intent: "смешанный" },
  { phrase: "8 в нумерологии", demand: 7785, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология 13 13", demand: 7399, priority: "P2", intent: "смешанный" },
  { phrase: "5 в нумерологии", demand: 7318, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы под сердцем", demand: 7253, priority: "P2", intent: "смешанный" },
  { phrase: "3 в нумерологии", demand: 6904, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы по дате расшифровка", demand: 6901, priority: "P2", intent: "смешанный" },
  { phrase: "какая матрица судьбы", demand: 6877, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы солнце", demand: 6841, priority: "P2", intent: "смешанный" },
  { phrase: "2 в нумерологии", demand: 6676, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы белое", demand: 6599, priority: "P2", intent: "смешанный" },
  { phrase: "бесплатная матрица судьбы с расшифровкой по дате", demand: 6552, priority: "P2", intent: "коммерческий" },
  { phrase: "белое солнце матрица судьбы", demand: 6483, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы по дате онлайн", demand: 6434, priority: "P2", intent: "коммерческий" },
  { phrase: "женщин значение нумерология", demand: 6337, priority: "P2", intent: "информационный" },
  { phrase: "нумерология по дате бесплатно", demand: 6217, priority: "P2", intent: "коммерческий" },
  { phrase: "нумерология 17 17", demand: 6177, priority: "P2", intent: "смешанный" },
  { phrase: "бесплатная нумерология рождения", demand: 6126, priority: "P2", intent: "коммерческий" },
  { phrase: "матрица судьбы что значат", demand: 6022, priority: "P2", intent: "коммерческий" },
  { phrase: "что значит матрица судьбы", demand: 6022, priority: "P2", intent: "информационный" },
  { phrase: "нумерология по дате рождения бесплатно", demand: 6022, priority: "P2", intent: "коммерческий" },
  { phrase: "матрица судьбы по дате рождения с расшифровкой", demand: 5967, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы по дате онлайн бесплатно", demand: 5874, priority: "P2", intent: "коммерческий" },
  { phrase: "матрица судьбы онлайн рождения", demand: 5752, priority: "P2", intent: "коммерческий" },
  { phrase: "1 в нумерологии", demand: 5656, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы по дате рождения онлайн", demand: 5625, priority: "P2", intent: "коммерческий" },
  { phrase: "нумерология расшифровка", demand: 5544, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы совместимость бесплатно", demand: 5508, priority: "P2", intent: "коммерческий" },
  { phrase: "нумерология имени", demand: 5303, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы отношения", demand: 5293, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы онлайн по дате рождения бесплатно", demand: 5108, priority: "P2", intent: "коммерческий" },
  { phrase: "значение цифр в нумерологии", demand: 4974, priority: "P2", intent: "информационный" },
  { phrase: "нумерология число дата", demand: 4847, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология дня", demand: 4790, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы мужчине", demand: 4692, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология рожденные", demand: 4649, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология судьбы", demand: 4616, priority: "P2", intent: "смешанный" },
  { phrase: "число даты рождения нумерология", demand: 4429, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы цифры", demand: 4285, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы женщина", demand: 4136, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология по числу рождения", demand: 4087, priority: "P2", intent: "смешанный" },
  { phrase: "программа 6 матрица судьбы", demand: 4019, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология 2222", demand: 3986, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология времени", demand: 3957, priority: "P2", intent: "смешанный" },
  { phrase: "что означает матрица судьбы", demand: 3906, priority: "P2", intent: "информационный" },
  { phrase: "нумерология любви", demand: 3872, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология расшифровка даты", demand: 3804, priority: "P2", intent: "смешанный" },
  { phrase: "14 нумерология значение", demand: 3747, priority: "P2", intent: "информационный" },
  { phrase: "суть матрица судьбы", demand: 3738, priority: "P2", intent: "информационный" },
  { phrase: "нумерология бесплатная расшифровка", demand: 3722, priority: "P2", intent: "коммерческий" },
  { phrase: "матрица судьбы совместимость онлайн", demand: 3718, priority: "P2", intent: "коммерческий" },
  { phrase: "программа 8 матрица судьбы", demand: 3595, priority: "P2", intent: "смешанный" },
  { phrase: "расшифровка даты рождения по нумерологии", demand: 3576, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы программа 10", demand: 3572, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология значение даты", demand: 3567, priority: "P2", intent: "информационный" },
  { phrase: "программа 7 матрица судьбы", demand: 3536, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость по нумерологии по дате", demand: 3520, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость по нумерологии рождения", demand: 3437, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология по дате рождения совместимость", demand: 3400, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология цифры рождения", demand: 3390, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология расчет", demand: 3387, priority: "P2", intent: "коммерческий" },
  { phrase: "число жизненного пути", demand: 3349, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология число 9", demand: 3337, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология по дате бесплатно с расшифровкой", demand: 3335, priority: "P2", intent: "коммерческий" },
  { phrase: "нумерология жизни", demand: 3332, priority: "P2", intent: "смешанный" },
  { phrase: "программа 9 матрица судьбы", demand: 3318, priority: "P2", intent: "смешанный" },
  { phrase: "01 01 нумерология", demand: 3317, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология 09 09", demand: 3294, priority: "P2", intent: "смешанный" },
  { phrase: "что означают числа в нумерологии", demand: 3260, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология цифра дата", demand: 3248, priority: "P2", intent: "смешанный" },
  { phrase: "23 нумерология значение", demand: 3239, priority: "P2", intent: "информационный" },
  { phrase: "11 в нумерологии", demand: 3235, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология 00", demand: 3205, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология по дате рождения бесплатно с расшифровкой", demand: 3199, priority: "P2", intent: "коммерческий" },
  { phrase: "нумерология онлайн бесплатно", demand: 3177, priority: "P2", intent: "коммерческий" },
  { phrase: "число женщины в нумерологии", demand: 3160, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология 02 02", demand: 3140, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология пифагора", demand: 3091, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология 1111", demand: 3060, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология свадьбы", demand: 3003, priority: "P2", intent: "смешанный" },
  { phrase: "миссия в нумерологии", demand: 2997, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы любовь", demand: 2988, priority: "P2", intent: "смешанный" },
  { phrase: "22 в нумерологии", demand: 2962, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология 17 значение", demand: 2934, priority: "P2", intent: "информационный" },
  { phrase: "нумерология 55", demand: 2915, priority: "P2", intent: "смешанный" },
  { phrase: "рожденные числа нумерология", demand: 2874, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология 08 08", demand: 2844, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы кармический хвост 9", demand: 2792, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы человека", demand: 2773, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология дома", demand: 2771, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология машины", demand: 2767, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология 2121", demand: 2751, priority: "P2", intent: "смешанный" },
  { phrase: "доллар матрица судьбы", demand: 2698, priority: "P2", intent: "смешанный" },
  { phrase: "личная матрица судьбы", demand: 2688, priority: "P2", intent: "смешанный" },
  { phrase: "1717 нумерология", demand: 2687, priority: "P2", intent: "смешанный" },
  { phrase: "число судьбы женщины", demand: 2676, priority: "P2", intent: "смешанный" },
  { phrase: "предназначение по дате рождения", demand: 2650, priority: "P2", intent: "информационный" },
  { phrase: "матрица судьбы дети", demand: 2645, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология число 6", demand: 2591, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология по дате рождения женщины", demand: 2564, priority: "P2", intent: "смешанный" },
  { phrase: "число 9 в нумерологии", demand: 2461, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы 18 9 9", demand: 2413, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы калькулятор онлайн", demand: 2373, priority: "P2", intent: "коммерческий" },
  { phrase: "матрица судьбы род", demand: 2336, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы кармический хвост 3", demand: 2325, priority: "P2", intent: "смешанный" },
  { phrase: "денежная матрица судьбы", demand: 2320, priority: "P2", intent: "смешанный" },
  { phrase: "нумерология по дате рождения значение", demand: 2258, priority: "P2", intent: "информационный" },
  { phrase: "число 7 в нумерологии", demand: 2243, priority: "P2", intent: "смешанный" },
] as const;
