import type { SemanticPhrase } from "../semantic-core-types";

// «Вместе» — 149 фраз, замер Wordstat 27.07.2026 (Россия, broad).
// Порог отбора — 100 показов в месяц: фразы ниже в ядро не попадают.
export const PAIR_PHRASES: readonly SemanticPhrase[] = [
  { phrase: "токсичные отношения", demand: 21763, priority: "P1", intent: "смешанный" },
  { phrase: "тест на отношения", demand: 15882, priority: "P1", intent: "коммерческий" },
  { phrase: "тест для пары", demand: 15839, priority: "P1", intent: "коммерческий" },
  { phrase: "тесты для пар", demand: 14276, priority: "P1", intent: "коммерческий" },
  { phrase: "кризис в отношениях", demand: 10457, priority: "P1", intent: "смешанный" },
  { phrase: "как наладить отношения", demand: 9128, priority: "P1", intent: "информационный" },
  { phrase: "теста для двоих", demand: 8485, priority: "P1", intent: "коммерческий" },
  { phrase: "тесты для двоих", demand: 8458, priority: "P1", intent: "коммерческий" },
  { phrase: "как сохранить отношения", demand: 5621, priority: "P1", intent: "смешанный" },
  { phrase: "теста совместимость для двоих", demand: 5230, priority: "P1", intent: "коммерческий" },
  { phrase: "тест на совместимость для двоих", demand: 5191, priority: "P1", intent: "коммерческий" },
  { phrase: "тест для пары в отношениях", demand: 1867, priority: "P1", intent: "коммерческий" },
  { phrase: "тесты для пар в отношениях", demand: 1867, priority: "P1", intent: "коммерческий" },
  { phrase: "тест на тип отношений", demand: 1841, priority: "P1", intent: "коммерческий" },
  { phrase: "кризис в отношениях по годам", demand: 1747, priority: "P1", intent: "смешанный" },
  { phrase: "тест на привязанность в отношениях", demand: 1478, priority: "P1", intent: "коммерческий" },
  { phrase: "тест на абьюзера в отношениях", demand: 1382, priority: "P1", intent: "коммерческий" },
  { phrase: "тест на тип привязанности в отношениях", demand: 1326, priority: "P1", intent: "коммерческий" },
  { phrase: "тест для пар для двоих", demand: 1314, priority: "P1", intent: "коммерческий" },
  { phrase: "тесты для двоих онлайн", demand: 1285, priority: "P1", intent: "коммерческий" },
  { phrase: "как наладить отношения с мужем", demand: 1137, priority: "P1", intent: "информационный" },
  { phrase: "кризис отношений в браке", demand: 1032, priority: "P1", intent: "смешанный" },
  { phrase: "как наладить отношения после", demand: 978, priority: "P1", intent: "информационный" },
  { phrase: "тест на совместимость онлайн для двоих", demand: 948, priority: "P1", intent: "коммерческий" },
  { phrase: "тест бывшие отношения", demand: 914, priority: "P1", intent: "коммерческий" },
  { phrase: "тесты онлайн отношения", demand: 904, priority: "P1", intent: "коммерческий" },
  { phrase: "тест какой ты в отношениях", demand: 872, priority: "P1", intent: "коммерческий" },
  { phrase: "тест на флаг в отношениях", demand: 839, priority: "P1", intent: "коммерческий" },
  { phrase: "тест для пары на двоих", demand: 827, priority: "P1", intent: "коммерческий" },
  { phrase: "кризис в отношениях с мужем", demand: 804, priority: "P1", intent: "смешанный" },
  { phrase: "тест на ред флаг в отношениях", demand: 721, priority: "P2", intent: "коммерческий" },
  { phrase: "тесты для парочек", demand: 714, priority: "P2", intent: "коммерческий" },
  { phrase: "3 кризиса в отношениях", demand: 712, priority: "P2", intent: "смешанный" },
  { phrase: "тесты про отношения", demand: 669, priority: "P2", intent: "коммерческий" },
  { phrase: "как сохранить отношения после", demand: 622, priority: "P2", intent: "смешанный" },
  { phrase: "как наладить отношения с ребенком", demand: 614, priority: "P2", intent: "информационный" },
  { phrase: "тест на отношения с парнем", demand: 594, priority: "P2", intent: "коммерческий" },
  { phrase: "тесты отношения бесплатно", demand: 555, priority: "P2", intent: "коммерческий" },
  { phrase: "какие кризисы в отношениях", demand: 534, priority: "P2", intent: "смешанный" },
  { phrase: "как наладить отношения с дочерью", demand: 532, priority: "P2", intent: "информационный" },
  { phrase: "тест на отношения для двоих", demand: 521, priority: "P2", intent: "коммерческий" },
  { phrase: "кризис 3 лет в отношениях", demand: 494, priority: "P2", intent: "смешанный" },
  { phrase: "кризис в семейных отношениях", demand: 471, priority: "P2", intent: "смешанный" },
  { phrase: "как наладить отношения со", demand: 470, priority: "P2", intent: "информационный" },
  { phrase: "тест на совместимость пары для двоих", demand: 463, priority: "P2", intent: "коммерческий" },
  { phrase: "тесты для пар на совместимость для двоих", demand: 463, priority: "P2", intent: "коммерческий" },
  { phrase: "как наладить отношения с женой", demand: 462, priority: "P2", intent: "информационный" },
  { phrase: "как наладить отношения советы", demand: 457, priority: "P2", intent: "информационный" },
  { phrase: "тест на отношения вопросы", demand: 457, priority: "P2", intent: "коммерческий" },
  { phrase: "психологический тест на отношения", demand: 437, priority: "P2", intent: "коммерческий" },
  { phrase: "тест для двоих бесплатно", demand: 428, priority: "P2", intent: "коммерческий" },
  { phrase: "кризисы в отношениях по годам в браке", demand: 411, priority: "P2", intent: "смешанный" },
  { phrase: "тесты для двоих друзей", demand: 410, priority: "P2", intent: "коммерческий" },
  { phrase: "тест сколько отношений", demand: 408, priority: "P2", intent: "коммерческий" },
  { phrase: "как наладить отношения с сыном", demand: 392, priority: "P2", intent: "информационный" },
  { phrase: "тест на совместимость для двоих бесплатно", demand: 388, priority: "P2", intent: "коммерческий" },
  { phrase: "тест на отношения с ответами", demand: 379, priority: "P2", intent: "коммерческий" },
  { phrase: "как сохранить отношения на расстоянии", demand: 375, priority: "P2", intent: "смешанный" },
  { phrase: "как наладить отношения с мамой", demand: 371, priority: "P2", intent: "информационный" },
  { phrase: "как наладить отношения между", demand: 366, priority: "P2", intent: "информационный" },
  { phrase: "5 кризисов в отношениях", demand: 361, priority: "P2", intent: "смешанный" },
  { phrase: "тест на абьюзера для двоих", demand: 360, priority: "P2", intent: "коммерческий" },
  { phrase: "три кризиса в отношениях", demand: 359, priority: "P2", intent: "смешанный" },
  { phrase: "как наладить отношения с подростком", demand: 358, priority: "P2", intent: "информационный" },
  { phrase: "тесты ваше отношение", demand: 351, priority: "P2", intent: "коммерческий" },
  { phrase: "кризис в отношениях 7", demand: 343, priority: "P2", intent: "смешанный" },
  { phrase: "кризис в отношениях после", demand: 327, priority: "P2", intent: "смешанный" },
  { phrase: "тесты для двоих на знание", demand: 326, priority: "P2", intent: "коммерческий" },
  { phrase: "семейный тест отношений", demand: 326, priority: "P2", intent: "коммерческий" },
  { phrase: "тест на совместимость для двоих отвечают", demand: 325, priority: "P2", intent: "коммерческий" },
  { phrase: "кризисы в отношениях периоды", demand: 322, priority: "P2", intent: "смешанный" },
  { phrase: "тест для двоих отвечают оба", demand: 319, priority: "P2", intent: "коммерческий" },
  { phrase: "тест какой тип привязанности в отношениях", demand: 317, priority: "P2", intent: "коммерческий" },
  { phrase: "тест на совместимость для двоих отвечают оба", demand: 315, priority: "P2", intent: "коммерческий" },
  { phrase: "тест на абьюзивные отношения", demand: 310, priority: "P2", intent: "коммерческий" },
  { phrase: "способы как сохранить отношения", demand: 307, priority: "P2", intent: "смешанный" },
  { phrase: "кризис трех лет в отношениях", demand: 302, priority: "P2", intent: "смешанный" },
  { phrase: "как наладить отношения на грани", demand: 302, priority: "P2", intent: "информационный" },
  { phrase: "кризис в отношениях с детьми", demand: 298, priority: "P2", intent: "смешанный" },
  { phrase: "кризис в отношениях 5 лет", demand: 297, priority: "P2", intent: "смешанный" },
  { phrase: "тест на абьюзера в отношениях для двоих", demand: 297, priority: "P2", intent: "коммерческий" },
  { phrase: "ии тест отношений", demand: 296, priority: "P2", intent: "коммерческий" },
  { phrase: "кризис в отношениях 7 лет", demand: 288, priority: "P2", intent: "смешанный" },
  { phrase: "тест оценка отношений", demand: 288, priority: "P2", intent: "коммерческий" },
  { phrase: "как сохранить хорошие отношения", demand: 282, priority: "P2", intent: "смешанный" },
  { phrase: "тест на отношения с девушкой", demand: 278, priority: "P2", intent: "коммерческий" },
  { phrase: "эмоциональные отношения тест", demand: 277, priority: "P2", intent: "коммерческий" },
  { phrase: "как наладить отношения с бывшим", demand: 273, priority: "P2", intent: "информационный" },
  { phrase: "момент в отношениях тест", demand: 271, priority: "P2", intent: "коммерческий" },
  { phrase: "как сохранить отношения с мужем", demand: 267, priority: "P2", intent: "смешанный" },
  { phrase: "как пережить кризис в отношениях", demand: 259, priority: "P2", intent: "информационный" },
  { phrase: "как сохранить отношения с ребенком", demand: 258, priority: "P2", intent: "смешанный" },
  { phrase: "тест для двоих на знание друг друга", demand: 257, priority: "P2", intent: "коммерческий" },
  { phrase: "тест на человека в отношениях", demand: 257, priority: "P2", intent: "коммерческий" },
  { phrase: "жертва в отношениях тест", demand: 255, priority: "P2", intent: "коммерческий" },
  { phrase: "тест на ревность в отношениях", demand: 254, priority: "P2", intent: "коммерческий" },
  { phrase: "первые кризисы в отношениях", demand: 253, priority: "P2", intent: "смешанный" },
  { phrase: "первый кризис в отношениях", demand: 253, priority: "P2", intent: "смешанный" },
  { phrase: "как наладить отношения с мужчиной", demand: 246, priority: "P2", intent: "информационный" },
  { phrase: "кризисы в отношениях мужчины и женщины", demand: 244, priority: "P2", intent: "смешанный" },
  { phrase: "тест на знание отношений", demand: 242, priority: "P2", intent: "коммерческий" },
  { phrase: "советы психолога как наладить отношения", demand: 234, priority: "P2", intent: "информационный" },
  { phrase: "как наладить отношения на грани развода", demand: 232, priority: "P2", intent: "информационный" },
  { phrase: "тест на прошедшие отношения", demand: 231, priority: "P2", intent: "коммерческий" },
  { phrase: "пройти тест на отношения", demand: 230, priority: "P2", intent: "коммерческий" },
  { phrase: "тест на любовь в отношениях", demand: 229, priority: "P2", intent: "коммерческий" },
  { phrase: "кризис в отношениях с мужем по годам", demand: 224, priority: "P2", intent: "смешанный" },
  { phrase: "кризисы в отношениях между мужчиной", demand: 223, priority: "P2", intent: "смешанный" },
  { phrase: "кризис в отношениях через", demand: 221, priority: "P2", intent: "смешанный" },
  { phrase: "кризисы в отношениях между мужчиной и женщиной", demand: 220, priority: "P2", intent: "смешанный" },
  { phrase: "как наладить отношения с девушкой", demand: 219, priority: "P2", intent: "информационный" },
  { phrase: "кризис в отношения в семье", demand: 218, priority: "P2", intent: "смешанный" },
  { phrase: "когда в отношениях наступает кризис", demand: 210, priority: "P2", intent: "смешанный" },
  { phrase: "как наладить отношения с человеком", demand: 209, priority: "P2", intent: "информационный" },
  { phrase: "как сохранять близкие отношения", demand: 209, priority: "P2", intent: "смешанный" },
  { phrase: "как наладить отношения с мужем после", demand: 208, priority: "P2", intent: "информационный" },
  { phrase: "кризис в отношениях что делать", demand: 206, priority: "P2", intent: "смешанный" },
  { phrase: "тест отношений подростков", demand: 205, priority: "P2", intent: "коммерческий" },
  { phrase: "тест отношения жизни", demand: 205, priority: "P2", intent: "коммерческий" },
  { phrase: "как наладить отношения в семье", demand: 201, priority: "P2", intent: "информационный" },
  { phrase: "как наладить отношения с парнем", demand: 200, priority: "P2", intent: "информационный" },
  { phrase: "как сохранить отношения с мужчиной", demand: 198, priority: "P2", intent: "смешанный" },
  { phrase: "тест мужчине на отношения", demand: 197, priority: "P2", intent: "коммерческий" },
  { phrase: "кризис в начале отношений", demand: 196, priority: "P2", intent: "смешанный" },
  { phrase: "тест связанный с отношениями", demand: 196, priority: "P2", intent: "коммерческий" },
  { phrase: "виды отношений тест", demand: 196, priority: "P2", intent: "коммерческий" },
  { phrase: "какой ты флаг в отношениях тест", demand: 195, priority: "P2", intent: "коммерческий" },
  { phrase: "сколько кризисов в отношениях", demand: 194, priority: "P2", intent: "смешанный" },
  { phrase: "когда бывает кризис в отношениях", demand: 193, priority: "P2", intent: "смешанный" },
  { phrase: "как наладить отношения после ссоры", demand: 193, priority: "P2", intent: "информационный" },
  { phrase: "тест на здоровые отношения", demand: 193, priority: "P2", intent: "коммерческий" },
  { phrase: "тест на созависимость в отношениях", demand: 192, priority: "P2", intent: "коммерческий" },
  { phrase: "какой вы момент в отношениях тест", demand: 191, priority: "P2", intent: "коммерческий" },
  { phrase: "тесты год отношений", demand: 190, priority: "P2", intent: "коммерческий" },
  { phrase: "как наладить отношения с мужем на грани", demand: 188, priority: "P2", intent: "информационный" },
  { phrase: "тест на хорошие отношения", demand: 188, priority: "P2", intent: "коммерческий" },
  { phrase: "как наладить отношения с другом", demand: 185, priority: "P2", intent: "информационный" },
  { phrase: "тест на отношения друзей", demand: 184, priority: "P2", intent: "коммерческий" },
  { phrase: "тесты для двоих онлайн бесплатно", demand: 183, priority: "P2", intent: "коммерческий" },
  { phrase: "измена как сохранить отношения", demand: 181, priority: "P2", intent: "смешанный" },
  { phrase: "тест на партнера в отношениях", demand: 180, priority: "P2", intent: "коммерческий" },
  { phrase: "как сохранить отношения с парнем", demand: 179, priority: "P2", intent: "смешанный" },
  { phrase: "анализ отношений тест", demand: 178, priority: "P2", intent: "коммерческий" },
  { phrase: "тест отношений добрякова", demand: 178, priority: "P2", intent: "коммерческий" },
  { phrase: "советы как сохранить отношения", demand: 176, priority: "P2", intent: "смешанный" },
  { phrase: "тест на совместимость для двоих вопросы", demand: 175, priority: "P2", intent: "коммерческий" },
  { phrase: "тесты на совместимость для двоих онлайн бесплатно", demand: 174, priority: "P2", intent: "коммерческий" },
  { phrase: "тест какой ты тип в отношениях", demand: 174, priority: "P2", intent: "коммерческий" },
  { phrase: "кризис 1 года в отношениях", demand: 173, priority: "P2", intent: "смешанный" },
] as const;
