import type { SemanticPhrase } from "../semantic-core-types";

// «Происхождение фамилии» — 150 фраз, замер Wordstat 27.07.2026 (Россия, broad).
// Порог отбора — 100 показов в месяц: фразы ниже в ядро не попадают.
export const SURNAMESTORY_PHRASES: readonly SemanticPhrase[] = [
  { phrase: "происхождение фамилии", demand: 375376, priority: "P1", intent: "информационный" },
  { phrase: "суть фамилии", demand: 159902, priority: "P1", intent: "информационный" },
  { phrase: "родословная", demand: 146484, priority: "P1", intent: "смешанный" },
  { phrase: "русские фамилии", demand: 105325, priority: "P1", intent: "смешанный" },
  { phrase: "значение фамилии", demand: 87012, priority: "P1", intent: "информационный" },
  { phrase: "откуда фамилия", demand: 86860, priority: "P1", intent: "информационный" },
  { phrase: "какой национальности фамилия", demand: 74870, priority: "P1", intent: "смешанный" },
  { phrase: "красивые фамилии", demand: 68318, priority: "P1", intent: "смешанный" },
  { phrase: "генеалогическое", demand: 63116, priority: "P1", intent: "смешанный" },
  { phrase: "английские фамилии", demand: 59896, priority: "P1", intent: "смешанный" },
  { phrase: "фамилии означающие", demand: 47736, priority: "P1", intent: "информационный" },
  { phrase: "история фамилии", demand: 46783, priority: "P1", intent: "информационный" },
  { phrase: "происхождение фамилии национальность", demand: 44500, priority: "P1", intent: "информационный" },
  { phrase: "японские фамилии", demand: 43759, priority: "P1", intent: "смешанный" },
  { phrase: "что означает фамилия", demand: 42505, priority: "P1", intent: "информационный" },
  { phrase: "американские фамилии", demand: 37841, priority: "P1", intent: "смешанный" },
  { phrase: "генеалогическое древо", demand: 35203, priority: "P1", intent: "смешанный" },
  { phrase: "немецкие фамилии", demand: 33552, priority: "P1", intent: "смешанный" },
  { phrase: "фамилия родов", demand: 31454, priority: "P1", intent: "смешанный" },
  { phrase: "фамилия род", demand: 30528, priority: "P1", intent: "смешанный" },
  { phrase: "роль фамилии", demand: 29339, priority: "P1", intent: "смешанный" },
  { phrase: "архив фамилий", demand: 28080, priority: "P1", intent: "смешанный" },
  { phrase: "российские фамилии", demand: 26834, priority: "P1", intent: "смешанный" },
  { phrase: "популярные фамилии", demand: 25609, priority: "P1", intent: "смешанный" },
  { phrase: "известные фамилии", demand: 25449, priority: "P1", intent: "смешанный" },
  { phrase: "еврейские фамилии", demand: 24025, priority: "P1", intent: "смешанный" },
  { phrase: "настоящая фамилия национальность", demand: 22524, priority: "P1", intent: "смешанный" },
  { phrase: "что значить фамилия", demand: 21103, priority: "P1", intent: "информационный" },
  { phrase: "что значит фамилия", demand: 21098, priority: "P1", intent: "информационный" },
  { phrase: "генеалогия", demand: 19086, priority: "P1", intent: "смешанный" },
  { phrase: "редкие фамилии", demand: 16466, priority: "P2", intent: "смешанный" },
  { phrase: "фамилии со значением", demand: 8762, priority: "P2", intent: "информационный" },
  { phrase: "английские имена и фамилии", demand: 8202, priority: "P2", intent: "смешанный" },
  { phrase: "японские имена и фамилии", demand: 7477, priority: "P2", intent: "смешанный" },
  { phrase: "русские имена и фамилии", demand: 7380, priority: "P2", intent: "смешанный" },
  { phrase: "архив имен и фамилий", demand: 6803, priority: "P2", intent: "смешанный" },
  { phrase: "красивые имена и фамилии", demand: 6722, priority: "P2", intent: "смешанный" },
  { phrase: "национальность значение фамилии", demand: 6516, priority: "P2", intent: "информационный" },
  { phrase: "фамилии происхождение и значение национальность", demand: 6137, priority: "P2", intent: "информационный" },
  { phrase: "родословная семьи", demand: 5677, priority: "P2", intent: "смешанный" },
  { phrase: "история фамилии бесплатно", demand: 5381, priority: "P2", intent: "коммерческий" },
  { phrase: "американские имена и фамилии", demand: 5202, priority: "P2", intent: "смешанный" },
  { phrase: "родословное древо", demand: 5096, priority: "P2", intent: "смешанный" },
  { phrase: "кредитная история по фамилии", demand: 5056, priority: "P2", intent: "информационный" },
  { phrase: "кредитная история по фамилии бесплатно", demand: 4931, priority: "P2", intent: "коммерческий" },
  { phrase: "родословное дерево", demand: 4871, priority: "P2", intent: "смешанный" },
  { phrase: "родословная таргариенов", demand: 4636, priority: "P2", intent: "смешанный" },
  { phrase: "родословная бесплатно", demand: 4543, priority: "P2", intent: "коммерческий" },
  { phrase: "история фамилии происхождение", demand: 4333, priority: "P2", intent: "информационный" },
  { phrase: "родословная по фамилии", demand: 4317, priority: "P2", intent: "смешанный" },
  { phrase: "российские имена и фамилии", demand: 4170, priority: "P2", intent: "смешанный" },
  { phrase: "японские фамилии со значением", demand: 3664, priority: "P2", intent: "информационный" },
  { phrase: "родословная онлайн", demand: 3587, priority: "P2", intent: "коммерческий" },
  { phrase: "генеалогическое древо семьи", demand: 3585, priority: "P2", intent: "смешанный" },
  { phrase: "архив родословной", demand: 3197, priority: "P2", intent: "смешанный" },
  { phrase: "родословная щенка", demand: 3088, priority: "P2", intent: "смешанный" },
  { phrase: "генеалог", demand: 2933, priority: "P2", intent: "смешанный" },
  { phrase: "как узнать свою родословную", demand: 2891, priority: "P2", intent: "коммерческий" },
  { phrase: "генеалогический метод", demand: 2798, priority: "P2", intent: "смешанный" },
  { phrase: "какая родословная", demand: 2777, priority: "P2", intent: "смешанный" },
  { phrase: "без родословной", demand: 2761, priority: "P2", intent: "смешанный" },
  { phrase: "моя родословная", demand: 2693, priority: "P2", intent: "смешанный" },
  { phrase: "где родословная", demand: 2444, priority: "P2", intent: "смешанный" },
  { phrase: "немецкие имена и фамилии", demand: 2353, priority: "P2", intent: "смешанный" },
  { phrase: "история фамилии онлайн", demand: 2340, priority: "P2", intent: "коммерческий" },
  { phrase: "история фамилии онлайн бесплатно", demand: 2289, priority: "P2", intent: "коммерческий" },
  { phrase: "родословная схема", demand: 2279, priority: "P2", intent: "смешанный" },
  { phrase: "происхождение фамилии страна", demand: 2263, priority: "P2", intent: "информационный" },
  { phrase: "родословная ркф", demand: 2157, priority: "P2", intent: "смешанный" },
  { phrase: "узнать историю фамилии", demand: 2156, priority: "P2", intent: "коммерческий" },
  { phrase: "родословная онлайн бесплатно", demand: 2094, priority: "P2", intent: "коммерческий" },
  { phrase: "чье происхождение фамилии", demand: 2087, priority: "P2", intent: "информационный" },
  { phrase: "кредитная история онлайн по фамилии", demand: 2050, priority: "P2", intent: "коммерческий" },
  { phrase: "кредитная история по фамилии бесплатно онлайн", demand: 2043, priority: "P2", intent: "коммерческий" },
  { phrase: "родословная ребенка", demand: 2034, priority: "P2", intent: "смешанный" },
  { phrase: "родословная ворон", demand: 2031, priority: "P2", intent: "смешанный" },
  { phrase: "родословная ворона", demand: 2031, priority: "P2", intent: "смешанный" },
  { phrase: "родословная воронов", demand: 2030, priority: "P2", intent: "смешанный" },
  { phrase: "история фамилии имени", demand: 1969, priority: "P2", intent: "информационный" },
  { phrase: "значение имени и фамилии", demand: 1966, priority: "P2", intent: "информационный" },
  { phrase: "откуда происхождение фамилии", demand: 1918, priority: "P2", intent: "информационный" },
  { phrase: "родословная это", demand: 1916, priority: "P2", intent: "информационный" },
  { phrase: "японские имена и фамилии мужские", demand: 1885, priority: "P2", intent: "смешанный" },
  { phrase: "родословные признаки", demand: 1859, priority: "P2", intent: "информационный" },
  { phrase: "днк генеалогия", demand: 1825, priority: "P2", intent: "смешанный" },
  { phrase: "родословная фамилии бесплатно", demand: 1820, priority: "P2", intent: "коммерческий" },
  { phrase: "происхождение русских фамилий", demand: 1812, priority: "P2", intent: "информационный" },
  { phrase: "японские женские имена и фамилии", demand: 1810, priority: "P2", intent: "смешанный" },
  { phrase: "романов родословная", demand: 1804, priority: "P2", intent: "смешанный" },
  { phrase: "метрика родословная", demand: 1774, priority: "P2", intent: "смешанный" },
  { phrase: "родословная романовых", demand: 1743, priority: "P2", intent: "смешанный" },
  { phrase: "история фамилии без", demand: 1682, priority: "P2", intent: "информационный" },
  { phrase: "родословная русских", demand: 1663, priority: "P2", intent: "смешанный" },
  { phrase: "узнать историю фамилии бесплатно", demand: 1661, priority: "P2", intent: "коммерческий" },
  { phrase: "родословная 4", demand: 1644, priority: "P2", intent: "смешанный" },
  { phrase: "составление родословной", demand: 1625, priority: "P2", intent: "смешанный" },
  { phrase: "популярные имена и фамилии", demand: 1612, priority: "P2", intent: "смешанный" },
  { phrase: "родословная геншин", demand: 1606, priority: "P2", intent: "смешанный" },
  { phrase: "история имя и фамилия", demand: 1537, priority: "P2", intent: "информационный" },
  { phrase: "узнать кредитную историю по фамилии", demand: 1530, priority: "P2", intent: "коммерческий" },
  { phrase: "история фамилий официальный", demand: 1517, priority: "P2", intent: "информационный" },
  { phrase: "узнать кредитную историю бесплатно по фамилии", demand: 1508, priority: "P2", intent: "коммерческий" },
  { phrase: "родословная ворон геншин", demand: 1477, priority: "P2", intent: "смешанный" },
  { phrase: "родословная ворона геншин", demand: 1477, priority: "P2", intent: "смешанный" },
  { phrase: "родословная воронов геншин", demand: 1477, priority: "P2", intent: "смешанный" },
  { phrase: "происхождение фамилии имени", demand: 1422, priority: "P2", intent: "информационный" },
  { phrase: "родословная 3", demand: 1415, priority: "P2", intent: "смешанный" },
  { phrase: "родословная драконов", demand: 1404, priority: "P2", intent: "смешанный" },
  { phrase: "родословная генеалогическое", demand: 1384, priority: "P2", intent: "смешанный" },
  { phrase: "дворянская родословная", demand: 1345, priority: "P2", intent: "смешанный" },
  { phrase: "родословная родителей", demand: 1335, priority: "P2", intent: "смешанный" },
  { phrase: "родословная князя", demand: 1301, priority: "P2", intent: "смешанный" },
  { phrase: "дом родословная", demand: 1295, priority: "P2", intent: "смешанный" },
  { phrase: "архивы родословной по фамилии", demand: 1293, priority: "P2", intent: "смешанный" },
  { phrase: "история родословной", demand: 1244, priority: "P2", intent: "информационный" },
  { phrase: "хорошая родословная", demand: 1224, priority: "P2", intent: "смешанный" },
  { phrase: "изобрази родословную", demand: 1223, priority: "P2", intent: "смешанный" },
  { phrase: "ткачев родословная", demand: 1212, priority: "P2", intent: "смешанный" },
  { phrase: "всероссийское генеалогическое древо", demand: 1202, priority: "P2", intent: "смешанный" },
  { phrase: "происхождение фамилии родов", demand: 1176, priority: "P2", intent: "информационный" },
  { phrase: "история через фамилию", demand: 1176, priority: "P2", intent: "информационный" },
  { phrase: "родословная рода", demand: 1158, priority: "P2", intent: "смешанный" },
  { phrase: "родословная пушкина", demand: 1152, priority: "P2", intent: "смешанный" },
  { phrase: "как узнать свою родословную по фамилии", demand: 1142, priority: "P2", intent: "коммерческий" },
  { phrase: "родословные рисунки", demand: 1127, priority: "P2", intent: "смешанный" },
  { phrase: "женские фамилии со значением", demand: 1112, priority: "P2", intent: "информационный" },
  { phrase: "кредитное бюро историй по фамилии", demand: 1108, priority: "P2", intent: "информационный" },
  { phrase: "родословная цветов", demand: 1104, priority: "P2", intent: "смешанный" },
  { phrase: "бюро кредитных историй бесплатно по фамилии", demand: 1101, priority: "P2", intent: "коммерческий" },
  { phrase: "полная родословная", demand: 1092, priority: "P2", intent: "смешанный" },
  { phrase: "метод родословных", demand: 1080, priority: "P2", intent: "смешанный" },
  { phrase: "семейная родословная", demand: 1023, priority: "P2", intent: "смешанный" },
  { phrase: "анализ родословной", demand: 1013, priority: "P2", intent: "смешанный" },
  { phrase: "родословная шаблон", demand: 1011, priority: "P2", intent: "смешанный" },
  { phrase: "черная родословная", demand: 1000, priority: "P2", intent: "смешанный" },
  { phrase: "черных родословная", demand: 1000, priority: "P2", intent: "смешанный" },
  { phrase: "записать родословную", demand: 992, priority: "P2", intent: "смешанный" },
  { phrase: "андрей ткачев родословная", demand: 988, priority: "P2", intent: "смешанный" },
  { phrase: "петров родословная", demand: 978, priority: "P2", intent: "смешанный" },
  { phrase: "кусок родословной", demand: 973, priority: "P2", intent: "смешанный" },
  { phrase: "как сделать родословную", demand: 971, priority: "P2", intent: "смешанный" },
  { phrase: "фамилия какое значение", demand: 969, priority: "P2", intent: "информационный" },
  { phrase: "клесов генеалогия", demand: 899, priority: "P2", intent: "смешанный" },
  { phrase: "генеалогия это", demand: 888, priority: "P2", intent: "информационный" },
  { phrase: "дом дракона родословная", demand: 884, priority: "P2", intent: "смешанный" },
  { phrase: "николаев родословная", demand: 881, priority: "P2", intent: "смешанный" },
  { phrase: "родословная по 1 признаку", demand: 880, priority: "P2", intent: "смешанный" },
  { phrase: "клесов днк генеалогия", demand: 878, priority: "P2", intent: "смешанный" },
  { phrase: "родословные россии", demand: 876, priority: "P2", intent: "смешанный" },
  { phrase: "мужские фамилии со значением", demand: 874, priority: "P2", intent: "информационный" },
] as const;
