import type { SemanticPhrase } from "../semantic-core-types";

// «Совместимость по дате» — 140 фраз, замер Wordstat 27.07.2026 (Россия, broad).
// Порог отбора — 100 показов в месяц: фразы ниже в ядро не попадают.
export const SYNASTRY_PHRASES: readonly SemanticPhrase[] = [
  { phrase: "совместимость", demand: 2553561, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость мужчина", demand: 298866, priority: "P1", intent: "смешанный" },
  { phrase: "матрица совместимости", demand: 274370, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость женщина", demand: 272810, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость мужчины и женщины", demand: 187544, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость по дате", demand: 178941, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость по рождению", demand: 167086, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость по дате рождения", demand: 164920, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость знаков", demand: 121957, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость зодиаков", demand: 99505, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость знаков зодиака", demand: 98816, priority: "P1", intent: "смешанный" },
  { phrase: "знаки зодиака совместимость", demand: 98443, priority: "P1", intent: "смешанный" },
  { phrase: "мы будем вместе", demand: 80301, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость в отношениях", demand: 72838, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость в любви", demand: 68643, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость бесплатно", demand: 68409, priority: "P1", intent: "коммерческий" },
  { phrase: "синастрия", demand: 62458, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость онлайн", demand: 50829, priority: "P1", intent: "коммерческий" },
  { phrase: "совместимость между", demand: 49946, priority: "P1", intent: "смешанный" },
  { phrase: "полная совместимость", demand: 43455, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость между мужчиной", demand: 43196, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость между женщиной и женщиной", demand: 41283, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость между мужчиной и женщиной", demand: 41054, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость в любовных отношениях", demand: 38031, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость мужчины по дате", demand: 35700, priority: "P1", intent: "смешанный" },
  { phrase: "женщины мужчины рождения совместимость", demand: 34632, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость по дате женщина и женщина", demand: 33555, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость мужчины и женщины по дате", demand: 33448, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость по дате рождения женщины и женщины", demand: 33340, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость по дате рождения мужчины и женщины", demand: 33236, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость по дате рождения между", demand: 33113, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость по дате между мужчиной", demand: 32955, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость по дате рождения между мужчиной", demand: 32857, priority: "P2", intent: "смешанный" },
  { phrase: "гороскоп совместимости", demand: 32208, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость рождения между мужчиной и женщиной", demand: 31525, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость по дате между женщинами", demand: 31376, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость по дате рождения между женщинами", demand: 31276, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость между мужчиной женщиной по дате", demand: 31226, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость по дате рождения между мужчиной женщиной", demand: 31128, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость любовь мужчины", demand: 31076, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость женщины любви", demand: 30320, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость в браке", demand: 30026, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость мужчины женщины любви", demand: 29649, priority: "P2", intent: "смешанный" },
  { phrase: "теста совместимость", demand: 29124, priority: "P2", intent: "коммерческий" },
  { phrase: "совместимость знаков мужчины", demand: 28919, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость знаков женщины", demand: 27273, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость онлайн бесплатно", demand: 26937, priority: "P2", intent: "коммерческий" },
  { phrase: "тест на совместимость", demand: 26841, priority: "P2", intent: "коммерческий" },
  { phrase: "теста на совместимость", demand: 26841, priority: "P2", intent: "коммерческий" },
  { phrase: "какая совместимость", demand: 26241, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость по дате бесплатно", demand: 25639, priority: "P2", intent: "коммерческий" },
  { phrase: "совместимость по дате рождения бесплатно", demand: 24819, priority: "P2", intent: "коммерческий" },
  { phrase: "зодиака мужчина совместимость", demand: 24556, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость знаков зодиака мужчин", demand: 24428, priority: "P2", intent: "смешанный" },
  { phrase: "карта совместимости", demand: 23443, priority: "P2", intent: "смешанный" },
  { phrase: "кармическая совместимость", demand: 22528, priority: "P2", intent: "смешанный" },
  { phrase: "проверить совместимость", demand: 21616, priority: "P2", intent: "коммерческий" },
  { phrase: "совместимость по гороскопу", demand: 21117, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость в любви и браке", demand: 20726, priority: "P2", intent: "смешанный" },
  { phrase: "матрица совместимости бесплатно", demand: 19491, priority: "P2", intent: "коммерческий" },
  { phrase: "совместимость в процентах", demand: 18775, priority: "P2", intent: "смешанный" },
  { phrase: "мужчина рыба и женщина рыба совместимость", demand: 18676, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость знаков мужчина и женщина", demand: 18531, priority: "P2", intent: "смешанный" },
  { phrase: "хвост в совместимости", demand: 18486, priority: "P2", intent: "смешанный" },
  { phrase: "таблица совместимости", demand: 18158, priority: "P2", intent: "смешанный" },
  { phrase: "кармический хвост в совместимости", demand: 17850, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость знаков зодиака женщина и женщина", demand: 17516, priority: "P2", intent: "смешанный" },
  { phrase: "девушка и мужчина совместимость", demand: 17394, priority: "P2", intent: "смешанный" },
  { phrase: "лучшая совместимость", demand: 17166, priority: "P2", intent: "смешанный" },
  { phrase: "натальная карта совместимость", demand: 17123, priority: "P2", intent: "смешанный" },
  { phrase: "мужчины и женщины зодиаки совместимость", demand: 16864, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость знаков зодиака мужчин и женщин", demand: 16792, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость в браке мужчина", demand: 16004, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость в браке женщина", demand: 15847, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость мужчины и женщины в браке", demand: 15060, priority: "P2", intent: "смешанный" },
  { phrase: "матрица совместимости онлайн", demand: 14501, priority: "P2", intent: "коммерческий" },
  { phrase: "совместимость пар", demand: 13975, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость пары", demand: 13975, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость мужчины и женщины бесплатно", demand: 13448, priority: "P2", intent: "коммерческий" },
  { phrase: "проверка совместимости", demand: 13417, priority: "P2", intent: "смешанный" },
  { phrase: "женщина совместимость в любви и браке", demand: 12262, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость между мужчиной и женщиной бесплатно", demand: 11980, priority: "P2", intent: "коммерческий" },
  { phrase: "совместимость с расшифровкой", demand: 11708, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость любовь отношения", demand: 10845, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость по дате рождения между мужчиной бесплатно", demand: 10713, priority: "P2", intent: "коммерческий" },
  { phrase: "совместимость парня и девушки", demand: 10682, priority: "P2", intent: "смешанный" },
  { phrase: "синастрия соединение", demand: 10583, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость с расшифровкой бесплатно", demand: 10487, priority: "P2", intent: "коммерческий" },
  { phrase: "синастрия онлайн", demand: 10178, priority: "P2", intent: "коммерческий" },
  { phrase: "гороскоп совместимости женщины", demand: 10096, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость знаков зодиака лев", demand: 8782, priority: "P2", intent: "смешанный" },
  { phrase: "кармические совместимости в матрице", demand: 8652, priority: "P2", intent: "смешанный" },
  { phrase: "хвост в матрице совместимости", demand: 8297, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость по дате рождения онлайн", demand: 8133, priority: "P2", intent: "коммерческий" },
  { phrase: "кармический хвост в матрице совместимости", demand: 8016, priority: "P2", intent: "смешанный" },
  { phrase: "матрица совместимости онлайн бесплатно", demand: 8009, priority: "P2", intent: "коммерческий" },
  { phrase: "венера в синастрии", demand: 7194, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость по дате рождения с расшифровкой", demand: 7096, priority: "P2", intent: "смешанный" },
  { phrase: "синастрия луна", demand: 7047, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость по дате рождения бесплатно с расшифровкой", demand: 6890, priority: "P2", intent: "коммерческий" },
  { phrase: "синастрия домов", demand: 6846, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость знаков зодиака в любви", demand: 6732, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость людей", demand: 6588, priority: "P2", intent: "смешанный" },
  { phrase: "синастрия солнце", demand: 6193, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость по дате рождения онлайн бесплатно", demand: 6080, priority: "P2", intent: "коммерческий" },
  { phrase: "совместимость по нумерологии", demand: 5736, priority: "P2", intent: "смешанный" },
  { phrase: "синастрия марсов", demand: 5688, priority: "P2", intent: "смешанный" },
  { phrase: "знак зодиака совместимость с другими знаками", demand: 5583, priority: "P2", intent: "смешанный" },
  { phrase: "расшифровка матрицы совместимости", demand: 5573, priority: "P2", intent: "смешанный" },
  { phrase: "6 в матрице совместимости", demand: 5399, priority: "P2", intent: "смешанный" },
  { phrase: "центр совместимости в матрице", demand: 5378, priority: "P2", intent: "смешанный" },
  { phrase: "синастрия мужчины женщины", demand: 5353, priority: "P2", intent: "смешанный" },
  { phrase: "9 в матрице совместимости", demand: 5335, priority: "P2", intent: "смешанный" },
  { phrase: "мы будем вместе всегда", demand: 5038, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость с мужчиной по дате рождения", demand: 4719, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость с мужчиной по дате рождения бесплатно", demand: 4594, priority: "P2", intent: "коммерческий" },
  { phrase: "совместимость знаков зодиака по гороскопу", demand: 4537, priority: "P2", intent: "смешанный" },
  { phrase: "матрица совместимости по дате", demand: 4169, priority: "P2", intent: "смешанный" },
  { phrase: "программы в матрице совместимости", demand: 4040, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы аркан совместимости", demand: 4025, priority: "P2", intent: "смешанный" },
  { phrase: "матрица судьбы совместимость арканов", demand: 4025, priority: "P2", intent: "смешанный" },
  { phrase: "синастрия квадрат", demand: 4016, priority: "P2", intent: "смешанный" },
  { phrase: "мы будем вместе любимая", demand: 3999, priority: "P2", intent: "смешанный" },
  { phrase: "лилит в синастрии", demand: 3897, priority: "P2", intent: "смешанный" },
  { phrase: "плутон в синастрии", demand: 3794, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость по годам", demand: 3672, priority: "P2", intent: "смешанный" },
  { phrase: "12 в матрице совместимости", demand: 3645, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость матрицы рождения", demand: 3641, priority: "P2", intent: "смешанный" },
  { phrase: "арканы в матрице совместимости в центре", demand: 3641, priority: "P2", intent: "смешанный" },
  { phrase: "18 в матрице совместимости", demand: 3607, priority: "P2", intent: "смешанный" },
  { phrase: "11 в матрице совместимости", demand: 3606, priority: "P2", intent: "смешанный" },
  { phrase: "21 в матрице совместимости", demand: 3571, priority: "P2", intent: "смешанный" },
  { phrase: "матрица совместимости по дате рождения", demand: 3536, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость по дате рождения онлайн с расшифровкой", demand: 3527, priority: "P2", intent: "коммерческий" },
  { phrase: "15 в матрице совместимости", demand: 3482, priority: "P2", intent: "смешанный" },
  { phrase: "3 матрица совместимости", demand: 3441, priority: "P2", intent: "смешанный" },
  { phrase: "тест на совместимость мужчины", demand: 3387, priority: "P2", intent: "коммерческий" },
  { phrase: "тест на совместимость между", demand: 3377, priority: "P2", intent: "коммерческий" },
  { phrase: "тест на совместимость женщиной", demand: 3356, priority: "P2", intent: "коммерческий" },
  { phrase: "10 в матрице совместимости", demand: 3355, priority: "P2", intent: "смешанный" },
] as const;
