import type { SemanticPhrase } from "../semantic-core-types";

// «Расклад Таро» — 144 фраз, замер Wordstat 27.07.2026 (Россия, broad).
// Порог отбора — 100 показов в месяц: фразы ниже в ядро не попадают.
export const TAROT_PHRASES: readonly SemanticPhrase[] = [
  { phrase: "таро", demand: 4279871, priority: "P1", intent: "смешанный" },
  { phrase: "гадание", demand: 2049742, priority: "P1", intent: "смешанный" },
  { phrase: "карты таро", demand: 823597, priority: "P1", intent: "смешанный" },
  { phrase: "гадание онлайн", demand: 739479, priority: "P1", intent: "коммерческий" },
  { phrase: "расклад таро", demand: 558493, priority: "P1", intent: "смешанный" },
  { phrase: "значение таро", demand: 390716, priority: "P1", intent: "информационный" },
  { phrase: "таро онлайн", demand: 302671, priority: "P1", intent: "коммерческий" },
  { phrase: "гадание таро", demand: 268578, priority: "P1", intent: "смешанный" },
  { phrase: "гадание онлайн бесплатно", demand: 238553, priority: "P1", intent: "коммерческий" },
  { phrase: "таролог", demand: 140541, priority: "P1", intent: "смешанный" },
  { phrase: "таро бесплатно", demand: 127982, priority: "P1", intent: "коммерческий" },
  { phrase: "кубки таро", demand: 124320, priority: "P1", intent: "смешанный" },
  { phrase: "значение карт таро", demand: 114922, priority: "P1", intent: "информационный" },
  { phrase: "таро прогноз", demand: 96001, priority: "P1", intent: "смешанный" },
  { phrase: "таро в помощь", demand: 94233, priority: "P1", intent: "смешанный" },
  { phrase: "таро онлайн бесплатно", demand: 91369, priority: "P1", intent: "коммерческий" },
  { phrase: "гадание таро онлайн", demand: 90827, priority: "P1", intent: "коммерческий" },
  { phrase: "карты таро гадание", demand: 73290, priority: "P1", intent: "смешанный" },
  { phrase: "мечи в таро", demand: 66272, priority: "P1", intent: "смешанный" },
  { phrase: "жезлы в таро", demand: 61163, priority: "P1", intent: "смешанный" },
  { phrase: "карты таро онлайн", demand: 60972, priority: "P1", intent: "коммерческий" },
  { phrase: "пентакли в таро", demand: 58562, priority: "P1", intent: "смешанный" },
  { phrase: "расклад таро онлайн", demand: 57723, priority: "P1", intent: "коммерческий" },
  { phrase: "сочетание таро", demand: 57552, priority: "P1", intent: "смешанный" },
  { phrase: "гадание на картах таро", demand: 56125, priority: "P1", intent: "смешанный" },
  { phrase: "значение картов таро", demand: 51502, priority: "P1", intent: "информационный" },
  { phrase: "таро уэйта", demand: 51365, priority: "P1", intent: "смешанный" },
  { phrase: "таро для мужчин", demand: 50721, priority: "P1", intent: "смешанный" },
  { phrase: "таро на отношения", demand: 50634, priority: "P1", intent: "смешанный" },
  { phrase: "перевернутые таро", demand: 48379, priority: "P1", intent: "смешанный" },
  { phrase: "смерть таро", demand: 47739, priority: "P2", intent: "смешанный" },
  { phrase: "таро дня", demand: 47462, priority: "P2", intent: "смешанный" },
  { phrase: "карты таро расклад", demand: 46245, priority: "P2", intent: "смешанный" },
  { phrase: "расклад таро бесплатно", demand: 39123, priority: "P2", intent: "коммерческий" },
  { phrase: "таро означающие", demand: 38008, priority: "P2", intent: "информационный" },
  { phrase: "ближайшие гадания онлайн", demand: 37988, priority: "P2", intent: "коммерческий" },
  { phrase: "мечи в таро значение", demand: 36052, priority: "P2", intent: "информационный" },
  { phrase: "таро расклад с ниной", demand: 35887, priority: "P2", intent: "смешанный" },
  { phrase: "луна таро", demand: 35676, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на мужчину онлайн", demand: 35353, priority: "P2", intent: "коммерческий" },
  { phrase: "таро на будущее", demand: 34722, priority: "P2", intent: "смешанный" },
  { phrase: "колода таро", demand: 34650, priority: "P2", intent: "смешанный" },
  { phrase: "гадание таро онлайн бесплатно", demand: 34191, priority: "P2", intent: "коммерческий" },
  { phrase: "сила таро", demand: 33919, priority: "P2", intent: "смешанный" },
  { phrase: "карты таро мечи", demand: 33402, priority: "P2", intent: "смешанный" },
  { phrase: "правдивое гадание онлайн", demand: 33385, priority: "P2", intent: "коммерческий" },
  { phrase: "расклад на отношения", demand: 33062, priority: "P2", intent: "смешанный" },
  { phrase: "таро карта дня", demand: 32523, priority: "P2", intent: "смешанный" },
  { phrase: "жрица таро", demand: 32494, priority: "P2", intent: "смешанный" },
  { phrase: "пентакли в таро значение", demand: 32215, priority: "P2", intent: "информационный" },
  { phrase: "карты таро бесплатно", demand: 31936, priority: "P2", intent: "коммерческий" },
  { phrase: "таро карта смерти", demand: 31923, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на любовь", demand: 31913, priority: "P2", intent: "смешанный" },
  { phrase: "жезлы в таро значение", demand: 31721, priority: "P2", intent: "информационный" },
  { phrase: "карты таро кубки", demand: 31457, priority: "P2", intent: "смешанный" },
  { phrase: "карты таро жезлы", demand: 30931, priority: "P2", intent: "смешанный" },
  { phrase: "гадание онлайн на ближней будущее", demand: 30914, priority: "P2", intent: "коммерческий" },
  { phrase: "кубки в таро значение", demand: 30412, priority: "P2", intent: "информационный" },
  { phrase: "перемен гадание онлайн", demand: 30355, priority: "P2", intent: "коммерческий" },
  { phrase: "карты таро пентакли", demand: 29682, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на картах онлайн", demand: 28752, priority: "P2", intent: "коммерческий" },
  { phrase: "правдивое гадание онлайн бесплатно", demand: 28500, priority: "P2", intent: "коммерческий" },
  { phrase: "тайное таро", demand: 28160, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на таро бесплатно", demand: 27063, priority: "P2", intent: "коммерческий" },
  { phrase: "таро ответов", demand: 26595, priority: "P2", intent: "смешанный" },
  { phrase: "тайны знания таро", demand: 25682, priority: "P2", intent: "смешанный" },
  { phrase: "тайные знания таро", demand: 25623, priority: "P2", intent: "смешанный" },
  { phrase: "что значит таро", demand: 25415, priority: "P2", intent: "информационный" },
  { phrase: "карты таро уэйта", demand: 25193, priority: "P2", intent: "смешанный" },
  { phrase: "карты таро означающие", demand: 25098, priority: "P2", intent: "информационный" },
  { phrase: "расклад таро онлайн бесплатно", demand: 25092, priority: "P2", intent: "коммерческий" },
  { phrase: "гадание на отношения", demand: 24519, priority: "P2", intent: "смешанный" },
  { phrase: "дьявол таро", demand: 24202, priority: "P2", intent: "смешанный" },
  { phrase: "сочетание карт таро", demand: 23687, priority: "P2", intent: "смешанный" },
  { phrase: "что означают карты таро", demand: 23391, priority: "P2", intent: "смешанный" },
  { phrase: "гадание онлайн да нет с точным", demand: 23154, priority: "P2", intent: "коммерческий" },
  { phrase: "звезда таро", demand: 23118, priority: "P2", intent: "смешанный" },
  { phrase: "императрица таро", demand: 22971, priority: "P2", intent: "смешанный" },
  { phrase: "солнце таро", demand: 22949, priority: "P2", intent: "смешанный" },
  { phrase: "что означает в таро", demand: 22905, priority: "P2", intent: "информационный" },
  { phrase: "таро трансформации", demand: 22548, priority: "P2", intent: "смешанный" },
  { phrase: "таро выпала", demand: 22141, priority: "P2", intent: "смешанный" },
  { phrase: "таро выпадает", demand: 22134, priority: "P2", intent: "смешанный" },
  { phrase: "онлайн гадание да нет с точным ответом", demand: 21717, priority: "P2", intent: "коммерческий" },
  { phrase: "карты таро онлайн бесплатно", demand: 21650, priority: "P2", intent: "коммерческий" },
  { phrase: "суд таро", demand: 21305, priority: "P2", intent: "смешанный" },
  { phrase: "архангел гадание онлайн", demand: 21042, priority: "P2", intent: "коммерческий" },
  { phrase: "короли в таро", demand: 20674, priority: "P2", intent: "смешанный" },
  { phrase: "маг таро", demand: 20470, priority: "P2", intent: "смешанный" },
  { phrase: "знаки таро", demand: 20422, priority: "P2", intent: "смешанный" },
  { phrase: "башня таро", demand: 20417, priority: "P2", intent: "смешанный" },
  { phrase: "таро в помощь расклад", demand: 20411, priority: "P2", intent: "смешанный" },
  { phrase: "расклад таро на отношения", demand: 20278, priority: "P2", intent: "смешанный" },
  { phrase: "влюбленные таро", demand: 20245, priority: "P2", intent: "смешанный" },
  { phrase: "яндекс таро", demand: 19947, priority: "P2", intent: "смешанный" },
  { phrase: "таро интеграции", demand: 19535, priority: "P2", intent: "смешанный" },
  { phrase: "колесо таро", demand: 19483, priority: "P2", intent: "смешанный" },
  { phrase: "таро на человека", demand: 18858, priority: "P2", intent: "смешанный" },
  { phrase: "таро на чувства", demand: 18680, priority: "P2", intent: "смешанный" },
  { phrase: "тузы в таро", demand: 18579, priority: "P2", intent: "смешанный" },
  { phrase: "таро на любовь", demand: 18575, priority: "P2", intent: "смешанный" },
  { phrase: "таро на бывшего", demand: 18565, priority: "P2", intent: "смешанный" },
  { phrase: "таро лев", demand: 18537, priority: "P2", intent: "смешанный" },
  { phrase: "император таро", demand: 18284, priority: "P2", intent: "смешанный" },
  { phrase: "рыцари в таро", demand: 18204, priority: "P2", intent: "смешанный" },
  { phrase: "колесница таро", demand: 18121, priority: "P2", intent: "смешанный" },
  { phrase: "магия таро", demand: 15820, priority: "P2", intent: "смешанный" },
  { phrase: "перевернутые карты таро", demand: 15785, priority: "P2", intent: "смешанный" },
  { phrase: "таро расклад для мужчин", demand: 15686, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на мужчину онлайн бесплатно", demand: 15396, priority: "P2", intent: "коммерческий" },
  { phrase: "таро на ситуацию", demand: 15171, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на картах онлайн бесплатно", demand: 15095, priority: "P2", intent: "коммерческий" },
  { phrase: "выпала карта таро", demand: 14893, priority: "P2", intent: "смешанный" },
  { phrase: "выпали карты таро", demand: 14890, priority: "P2", intent: "смешанный" },
  { phrase: "гадание таро на мужчину", demand: 14512, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на картах таро онлайн", demand: 14495, priority: "P2", intent: "коммерческий" },
  { phrase: "руны гадание онлайн", demand: 14311, priority: "P2", intent: "коммерческий" },
  { phrase: "любимое таро", demand: 14165, priority: "P2", intent: "смешанный" },
  { phrase: "гадание бесплатно онлайн точный ответ", demand: 14062, priority: "P2", intent: "коммерческий" },
  { phrase: "что значат карты таро", demand: 13714, priority: "P2", intent: "коммерческий" },
  { phrase: "что значит карты таро", demand: 13714, priority: "P2", intent: "информационный" },
  { phrase: "гадание да нет с точным бесплатно онлайн", demand: 13704, priority: "P2", intent: "коммерческий" },
  { phrase: "ответ да нет онлайн гадание бесплатно", demand: 13664, priority: "P2", intent: "коммерческий" },
  { phrase: "карты таро на отношения", demand: 13405, priority: "P2", intent: "смешанный" },
  { phrase: "колода карт таро", demand: 13086, priority: "P2", intent: "смешанный" },
  { phrase: "как гадать на таро", demand: 13063, priority: "P2", intent: "смешанный" },
  { phrase: "гадание на картах таро бесплатно", demand: 12793, priority: "P2", intent: "коммерческий" },
  { phrase: "гадание таро на будущее", demand: 12392, priority: "P2", intent: "смешанный" },
  { phrase: "гадание онлайн на кофейной", demand: 12163, priority: "P2", intent: "коммерческий" },
  { phrase: "гадание на гуще онлайн", demand: 12060, priority: "P2", intent: "коммерческий" },
  { phrase: "гадание на кофейной гуще онлайн", demand: 12019, priority: "P2", intent: "коммерческий" },
  { phrase: "расклад таро на будущее", demand: 11628, priority: "P2", intent: "смешанный" },
  { phrase: "карты таро на будущее", demand: 11583, priority: "P2", intent: "смешанный" },
  { phrase: "толкование карт таро", demand: 11538, priority: "P2", intent: "смешанный" },
  { phrase: "гадание онлайн будущее правдивое", demand: 11324, priority: "P2", intent: "коммерческий" },
  { phrase: "карта таро туз", demand: 11128, priority: "P2", intent: "смешанный" },
  { phrase: "карты таро на мужчину", demand: 10871, priority: "P2", intent: "смешанный" },
  { phrase: "гадание онлайн бесплатно перемена", demand: 10517, priority: "P2", intent: "коммерческий" },
  { phrase: "суть расклада таро", demand: 10197, priority: "P2", intent: "информационный" },
  { phrase: "расклады таро схемы", demand: 10084, priority: "P2", intent: "смешанный" },
  { phrase: "карта таро мир", demand: 10043, priority: "P2", intent: "смешанный" },
  { phrase: "расклад на любовь", demand: 9836, priority: "P2", intent: "смешанный" },
  { phrase: "таро 1 карта", demand: 9756, priority: "P2", intent: "смешанный" },
  { phrase: "гадание онлайн на отношения", demand: 9635, priority: "P2", intent: "коммерческий" },
] as const;
