import type { SemanticPhrase } from "../semantic-core-types";

// «Арканы судьбы» — 148 фраз, замер Wordstat 27.07.2026 (Россия, broad).
// Порог отбора — 100 показов в месяц: фразы ниже в ядро не попадают.
export const TAROTNUMEROLOGY_PHRASES: readonly SemanticPhrase[] = [
  { phrase: "аркан", demand: 1225355, priority: "P1", intent: "смешанный" },
  { phrase: "арканов", demand: 1225321, priority: "P1", intent: "смешанный" },
  { phrase: "аркан арканов", demand: 1218861, priority: "P1", intent: "смешанный" },
  { phrase: "матрица арканов", demand: 131381, priority: "P1", intent: "смешанный" },
  { phrase: "матрица аркан", demand: 131340, priority: "P1", intent: "смешанный" },
  { phrase: "арканы таро", demand: 102024, priority: "P1", intent: "смешанный" },
  { phrase: "арканов таро", demand: 101972, priority: "P1", intent: "смешанный" },
  { phrase: "судьба арканов", demand: 91701, priority: "P1", intent: "смешанный" },
  { phrase: "арканы судьбы", demand: 91699, priority: "P1", intent: "смешанный" },
  { phrase: "аркан совместимости", demand: 85543, priority: "P1", intent: "смешанный" },
  { phrase: "совместимость арканов", demand: 85528, priority: "P1", intent: "смешанный" },
  { phrase: "аркан матрица судьбы", demand: 80784, priority: "P1", intent: "смешанный" },
  { phrase: "матрица судьбы арканов", demand: 80784, priority: "P1", intent: "смешанный" },
  { phrase: "2 аркан", demand: 47250, priority: "P1", intent: "смешанный" },
  { phrase: "11 аркан", demand: 41283, priority: "P1", intent: "смешанный" },
  { phrase: "11 арканов", demand: 41281, priority: "P1", intent: "смешанный" },
  { phrase: "8 аркан", demand: 38792, priority: "P1", intent: "смешанный" },
  { phrase: "8 арканов", demand: 38792, priority: "P1", intent: "смешанный" },
  { phrase: "аркан по дате", demand: 38420, priority: "P1", intent: "смешанный" },
  { phrase: "5 аркан", demand: 37528, priority: "P1", intent: "смешанный" },
  { phrase: "5 арканов", demand: 37495, priority: "P1", intent: "смешанный" },
  { phrase: "арканов дата рождения", demand: 36873, priority: "P1", intent: "смешанный" },
  { phrase: "6 аркан", demand: 35908, priority: "P1", intent: "смешанный" },
  { phrase: "6 арканов", demand: 35899, priority: "P1", intent: "смешанный" },
  { phrase: "7 арканов", demand: 35517, priority: "P1", intent: "смешанный" },
  { phrase: "7 аркан", demand: 35515, priority: "P1", intent: "смешанный" },
  { phrase: "аркан по рождению", demand: 35111, priority: "P1", intent: "смешанный" },
  { phrase: "аркан по дате рождения", demand: 34584, priority: "P1", intent: "смешанный" },
  { phrase: "арканов по дате рождения", demand: 34583, priority: "P1", intent: "смешанный" },
  { phrase: "10 арканов", demand: 33262, priority: "P1", intent: "смешанный" },
  { phrase: "10 аркан", demand: 33178, priority: "P2", intent: "смешанный" },
  { phrase: "9 аркан", demand: 32771, priority: "P2", intent: "смешанный" },
  { phrase: "9 арканов", demand: 32755, priority: "P2", intent: "смешанный" },
  { phrase: "арканы значение", demand: 31756, priority: "P2", intent: "информационный" },
  { phrase: "значение арканов", demand: 31755, priority: "P2", intent: "информационный" },
  { phrase: "12 аркан", demand: 28342, priority: "P2", intent: "смешанный" },
  { phrase: "12 арканов", demand: 28324, priority: "P2", intent: "смешанный" },
  { phrase: "старшие арканы", demand: 26451, priority: "P2", intent: "смешанный" },
  { phrase: "старших арканов", demand: 26437, priority: "P2", intent: "смешанный" },
  { phrase: "3 арканов", demand: 26365, priority: "P2", intent: "смешанный" },
  { phrase: "3 аркан", demand: 26359, priority: "P2", intent: "смешанный" },
  { phrase: "20 аркан", demand: 25228, priority: "P2", intent: "смешанный" },
  { phrase: "20 арканов", demand: 25221, priority: "P2", intent: "смешанный" },
  { phrase: "18 аркан", demand: 24759, priority: "P2", intent: "смешанный" },
  { phrase: "18 арканов", demand: 24750, priority: "P2", intent: "смешанный" },
  { phrase: "15 аркан", demand: 24448, priority: "P2", intent: "смешанный" },
  { phrase: "13 аркан", demand: 23542, priority: "P2", intent: "смешанный" },
  { phrase: "13 арканов", demand: 23541, priority: "P2", intent: "смешанный" },
  { phrase: "4 аркан", demand: 23114, priority: "P2", intent: "смешанный" },
  { phrase: "14 аркан", demand: 23068, priority: "P2", intent: "смешанный" },
  { phrase: "матрица совместимости аркан", demand: 22428, priority: "P2", intent: "смешанный" },
  { phrase: "матрица совместимости арканов", demand: 22428, priority: "P2", intent: "смешанный" },
  { phrase: "16 аркан", demand: 21812, priority: "P2", intent: "смешанный" },
  { phrase: "16 арканов", demand: 21807, priority: "P2", intent: "смешанный" },
  { phrase: "22 аркан", demand: 21273, priority: "P2", intent: "смешанный" },
  { phrase: "22 арканов", demand: 21269, priority: "P2", intent: "смешанный" },
  { phrase: "17 аркан", demand: 21087, priority: "P2", intent: "смешанный" },
  { phrase: "19 аркан", demand: 20896, priority: "P2", intent: "смешанный" },
  { phrase: "19 арканов", demand: 20896, priority: "P2", intent: "смешанный" },
  { phrase: "21 аркан", demand: 20517, priority: "P2", intent: "смешанный" },
  { phrase: "аркан в центре", demand: 19873, priority: "P2", intent: "смешанный" },
  { phrase: "аркан человека", demand: 18355, priority: "P2", intent: "смешанный" },
  { phrase: "аркан отношений", demand: 15963, priority: "P2", intent: "смешанный" },
  { phrase: "отношение арканов", demand: 15953, priority: "P2", intent: "смешанный" },
  { phrase: "аркан карта", demand: 15677, priority: "P2", intent: "смешанный" },
  { phrase: "карта арканов", demand: 15672, priority: "P2", intent: "смешанный" },
  { phrase: "аркан бесплатно", demand: 15397, priority: "P2", intent: "коммерческий" },
  { phrase: "старшие арканы таро", demand: 14355, priority: "P2", intent: "смешанный" },
  { phrase: "таро старших арканов", demand: 14349, priority: "P2", intent: "смешанный" },
  { phrase: "1 аркан", demand: 14220, priority: "P2", intent: "смешанный" },
  { phrase: "что значат арканы", demand: 13856, priority: "P2", intent: "коммерческий" },
  { phrase: "что значит аркан", demand: 13856, priority: "P2", intent: "информационный" },
  { phrase: "что значит арканов", demand: 13852, priority: "P2", intent: "информационный" },
  { phrase: "аркан в центре матрицы", demand: 13374, priority: "P2", intent: "смешанный" },
  { phrase: "сердце аркана", demand: 13074, priority: "P2", intent: "смешанный" },
  { phrase: "аркан онлайн", demand: 11688, priority: "P2", intent: "коммерческий" },
  { phrase: "арканов онлайн", demand: 11687, priority: "P2", intent: "коммерческий" },
  { phrase: "аркан мужчина", demand: 11523, priority: "P2", intent: "смешанный" },
  { phrase: "арканы таро значение", demand: 10724, priority: "P2", intent: "информационный" },
  { phrase: "значение арканов таро", demand: 10723, priority: "P2", intent: "информационный" },
  { phrase: "карты таро арканы", demand: 8589, priority: "P2", intent: "смешанный" },
  { phrase: "карты таро арканов", demand: 8584, priority: "P2", intent: "смешанный" },
  { phrase: "какой я аркан", demand: 8134, priority: "P2", intent: "смешанный" },
  { phrase: "как узнать своих арканов", demand: 8124, priority: "P2", intent: "коммерческий" },
  { phrase: "как узнать свой аркан", demand: 8124, priority: "P2", intent: "коммерческий" },
  { phrase: "женщина аркан", demand: 7773, priority: "P2", intent: "смешанный" },
  { phrase: "аркан в центре матрицы судьбы", demand: 7442, priority: "P2", intent: "смешанный" },
  { phrase: "11 аркан в матрице", demand: 7312, priority: "P2", intent: "смешанный" },
  { phrase: "аркан маг", demand: 7188, priority: "P2", intent: "смешанный" },
  { phrase: "расчет аркана", demand: 7081, priority: "P2", intent: "коммерческий" },
  { phrase: "расчет арканов", demand: 7081, priority: "P2", intent: "коммерческий" },
  { phrase: "выпала аркана", demand: 7030, priority: "P2", intent: "смешанный" },
  { phrase: "выпадет аркана", demand: 7021, priority: "P2", intent: "смешанный" },
  { phrase: "темные арканы", demand: 6847, priority: "P2", intent: "смешанный" },
  { phrase: "8 аркан в матрице", demand: 6813, priority: "P2", intent: "смешанный" },
  { phrase: "5 аркан в матрице", demand: 6775, priority: "P2", intent: "смешанный" },
  { phrase: "7 аркан в матрице", demand: 6659, priority: "P2", intent: "смешанный" },
  { phrase: "6 аркан в матрице", demand: 6625, priority: "P2", intent: "смешанный" },
  { phrase: "аркан пары", demand: 6519, priority: "P2", intent: "смешанный" },
  { phrase: "арканы пар", demand: 6519, priority: "P2", intent: "смешанный" },
  { phrase: "пары арканов", demand: 6518, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость арканов по арканам", demand: 6428, priority: "P2", intent: "смешанный" },
  { phrase: "10 аркан в матрице", demand: 6326, priority: "P2", intent: "смешанный" },
  { phrase: "что означает аркан", demand: 5935, priority: "P2", intent: "информационный" },
  { phrase: "какой аркан рождения", demand: 5925, priority: "P2", intent: "смешанный" },
  { phrase: "9 аркан в матрице", demand: 5924, priority: "P2", intent: "смешанный" },
  { phrase: "калькулятор аркана", demand: 5804, priority: "P2", intent: "коммерческий" },
  { phrase: "калькулятор аркан арканов", demand: 5802, priority: "P2", intent: "коммерческий" },
  { phrase: "калькулятор арканов", demand: 5802, priority: "P2", intent: "коммерческий" },
  { phrase: "значение аркан в матрице", demand: 5792, priority: "P2", intent: "информационный" },
  { phrase: "значение арканов в матрице", demand: 5792, priority: "P2", intent: "информационный" },
  { phrase: "аркан сила", demand: 5628, priority: "P2", intent: "смешанный" },
  { phrase: "сила арканов", demand: 5626, priority: "P2", intent: "смешанный" },
  { phrase: "аркана в лавке конфет", demand: 5527, priority: "P2", intent: "смешанный" },
  { phrase: "5 аркан судьбы", demand: 5504, priority: "P2", intent: "смешанный" },
  { phrase: "значение аркана судьбы", demand: 5401, priority: "P2", intent: "информационный" },
  { phrase: "центр совместимости арканов", demand: 5375, priority: "P2", intent: "смешанный" },
  { phrase: "аркан помощи", demand: 5327, priority: "P2", intent: "смешанный" },
  { phrase: "арканы в центре совместимости", demand: 5261, priority: "P2", intent: "смешанный" },
  { phrase: "11 аркан судьбы", demand: 5242, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость арканов 15", demand: 5198, priority: "P2", intent: "смешанный" },
  { phrase: "арканы судьбы таро", demand: 5152, priority: "P2", intent: "смешанный" },
  { phrase: "аркана девушка", demand: 5142, priority: "P2", intent: "смешанный" },
  { phrase: "6 аркан судьбы", demand: 5123, priority: "P2", intent: "смешанный" },
  { phrase: "7 аркан судьбы", demand: 5104, priority: "P2", intent: "смешанный" },
  { phrase: "совместимость арканов 11", demand: 5082, priority: "P2", intent: "смешанный" },
  { phrase: "8 аркан судьбы", demand: 5028, priority: "P2", intent: "смешанный" },
  { phrase: "аркан личности", demand: 4896, priority: "P2", intent: "смешанный" },
  { phrase: "арканы судьбы в помощь", demand: 4869, priority: "P2", intent: "смешанный" },
  { phrase: "какой аркан по дате", demand: 4827, priority: "P2", intent: "смешанный" },
  { phrase: "аркан любви", demand: 4824, priority: "P2", intent: "смешанный" },
  { phrase: "любовь арканов", demand: 4817, priority: "P2", intent: "смешанный" },
  { phrase: "аркан онлайн бесплатно", demand: 4660, priority: "P2", intent: "коммерческий" },
  { phrase: "арканы в матрице судьбы значение", demand: 4654, priority: "P2", intent: "информационный" },
  { phrase: "значение арканов в матрице судьбы", demand: 4654, priority: "P2", intent: "информационный" },
  { phrase: "арканы года значение", demand: 4500, priority: "P2", intent: "информационный" },
  { phrase: "5 аркан в матрице судьбы", demand: 4425, priority: "P2", intent: "смешанный" },
  { phrase: "11 аркан таро", demand: 4409, priority: "P2", intent: "смешанный" },
  { phrase: "11 арканов таро", demand: 4409, priority: "P2", intent: "смешанный" },
  { phrase: "11 аркан в матрице судьбы", demand: 4408, priority: "P2", intent: "смешанный" },
  { phrase: "10 аркан судьбы", demand: 4381, priority: "P2", intent: "смешанный" },
  { phrase: "7 аркан в матрице судьбы", demand: 4281, priority: "P2", intent: "смешанный" },
  { phrase: "9 аркан судьба", demand: 4230, priority: "P2", intent: "смешанный" },
  { phrase: "8 аркан в матрице судьбы", demand: 4210, priority: "P2", intent: "смешанный" },
  { phrase: "аркан судьба совместимость", demand: 4163, priority: "P2", intent: "смешанный" },
  { phrase: "6 аркан в матрице судьбы", demand: 4158, priority: "P2", intent: "смешанный" },
  { phrase: "какой аркан по дате рождения", demand: 4071, priority: "P2", intent: "смешанный" },
  { phrase: "8 аркан таро", demand: 3994, priority: "P2", intent: "смешанный" },
] as const;
