ALTER TYPE "AIProvider" ADD VALUE IF NOT EXISTS 'GROQ';
ALTER TYPE "AIProvider" ADD VALUE IF NOT EXISTS 'MISTRAL';
ALTER TYPE "AIProvider" ADD VALUE IF NOT EXISTS 'CEREBRAS';
ALTER TYPE "AIProvider" ADD VALUE IF NOT EXISTS 'COHERE';

ALTER TABLE "ai_provider_models"
  ADD COLUMN IF NOT EXISTS "input_token_cost_micros" INTEGER,
  ADD COLUMN IF NOT EXISTS "output_token_cost_micros" INTEGER;
