ALTER TYPE "NotificationEvent" ADD VALUE IF NOT EXISTS 'ABANDONED_CHECKOUT';
ALTER TYPE "NotificationEvent" ADD VALUE IF NOT EXISTS 'REPORT_READY';
ALTER TYPE "NotificationEvent" ADD VALUE IF NOT EXISTS 'PARTNER_COMPLETED';
ALTER TYPE "NotificationEvent" ADD VALUE IF NOT EXISTS 'CIRCLE_READY';
ALTER TYPE "NotificationEvent" ADD VALUE IF NOT EXISTS 'ROUTE_REMINDER';
ALTER TYPE "NotificationEvent" ADD VALUE IF NOT EXISTS 'WEEKLY_DIGEST';
ALTER TYPE "NotificationEvent" ADD VALUE IF NOT EXISTS 'PRACTITIONER_DIGEST';
ALTER TYPE "NotificationEvent" ADD VALUE IF NOT EXISTS 'COMPLIANCE_ALERT';
