import { notFound } from "next/navigation";
import { MayaNatalWheel } from "../b506-b507-astrology/maya-wheel";
import { loadMayaAssets } from "../b506-b507-astrology/maya-assets";
import { buildNatalEphemerisWheel } from "@/lib/natal-ephemeris";
import { computeHoraryFacts } from "@/lib/horary";

export const dynamic = "force-dynamic";
const sections=[["Радикальность","Карту можно судить: вопрос сформулирован конкретно, момент зафиксирован один раз, ранний или поздний ASC не отменяет чтение."],["Главный сходящийся аспект","Сигнификаторы движутся к поддерживающему контакту, поэтому базовый ответ положительный. До него Луна встречает препятствие — это задержка, а не окончательный отказ."],["Рецепции","Предмет вопроса сильнее заинтересован в завершении сделки, чем кажется по внешней коммуникации. Ваша сторона сейчас зависит от проверки условий."],["Противоречие","Свидетельство соединения поддерживает «да», но положение Луны показывает, что текущая редакция условий неудобна. Эти показатели не усредняются: ответ остаётся условным."],["Срок и условие","Вероятное окно — две–три единицы времени, в контексте вопроса недели. Исход меняется, если документальная проверка выявит ограничение или одна сторона откажется пересматривать пункт договора."]];
export default function HoraryPreviewPage(){if(process.env.NODE_ENV==="production")notFound();const assets=loadMayaAssets();const wheel=buildNatalEphemerisWheel("12.07.2026 18:42 Москва");const facts=computeHoraryFacts(wheel,"Вопрос: Состоится ли покупка этой квартиры до конца месяца?\nКатегория: недвижимость");const rows=[["Момент","12.07.2026 · 18:42"],["Место","Москва"],["Кверент",facts.querent.label],["Квезит",facts.quesited.label]];return <main className="mx-auto w-full max-w-[1120px] px-5 pb-20 pt-10"><p className="soft-eyebrow">локальный макет · B509</p><h1 className="soft-h1 mt-2">Хорарная карта</h1><p className="soft-body mt-2 max-w-2xl">«Состоится ли покупка этой квартиры до конца месяца?» — один вопрос, одна серверная фиксация времени и места.</p><div className="mt-6 rounded-[22px] bg-[var(--soft-bordeaux)] p-5 text-white"><p className="soft-eyebrow text-[#f2c9ad]">прямой ответ</p><p className="font-heading text-2xl">Скорее да, но не на текущих условиях</p><p className="mt-2 max-w-3xl text-sm leading-relaxed text-white/80">Сигнификаторы сходятся, однако Луна сначала показывает препятствие. Проверка документов и пересмотр одного условия — то, что способно изменить исход.</p></div><section className="mt-8 grid items-start gap-8 lg:grid-cols-[minmax(0,1.1fr)_minmax(320px,.9fr)]"><MayaNatalWheel wheel={wheel} assets={assets} highlighted={[facts.querent.planet,facts.quesited.planet,"moon"]}/><div className="space-y-4"><div className="grid grid-cols-2 gap-3">{rows.map(([l,v])=><div key={l} className="rounded-2xl bg-[var(--soft-paper-deep)] p-3"><p className="soft-eyebrow text-[.6rem]">{l}</p><p className="mt-1 text-sm text-[var(--soft-bordeaux)]">{v}</p></div>)}</div>{sections.map(([h,p],i)=><details key={h} open={i===0} className="rounded-[18px] border border-[var(--soft-paper-edge)] bg-white/60 px-5 py-4"><summary className="cursor-pointer font-heading text-lg text-[var(--soft-bordeaux)]">{h}</summary><p className="soft-body mt-4">{p}</p></details>)}</div></section></main>}
